### ISSUE TITLE
Additional documentation inside support modules

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/CubiCal#100]
Latest PR added a bunch of features, but I noticed that the support modules such as dynoptparse, the logger and the plots submodule could all do with a documentation polish. This is obviously not critical, but I think it would be a good idea for maintainability.

**Comment by o-smirnov** [comment]
It's slowly getting there (you should see the state they started in!) We've actually been discussing extracting these into a separate package, since both DDFacet and CubiCal use them.

**Comment by JSKenyon** [comment]
@o-smirnov Absolutely - hence this really not being a critical issue. I am just drunk with power. Basically, as we fix things, we should just do the docs of functions in the vicinity. Lazily converge to pretty, documented code.
