### ISSUE TITLE
vext no longer installed automatically by astro-tigger

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/CubiCal#101]
astro-tigger no longer installs vext automatically when inside a virtualenv.

**Comment by JSKenyon** [comment]
This can be fixed by adding `astro-tigger[venv]` to the requirements section of setup.py.

**Comment by JSKenyon** [comment]
@o-smirnov We may have been hasty - I think that the vext logger bug is still alive and well. Turns out that setup.py had not been installing vext so the problem may not have appeared on your system. Using the current version of master, which correctly installs vext, I think all logging disappears again.

**Comment by JSKenyon** [comment]
Just managed to reproduce this on 14.04 on Ray.

**Comment by o-smirnov** [comment]
I think this is really #75 rearing its head again.
