### ISSUE TITLE
Bug associated with "min-bl" parameter

### ISSUE THREAD

**Issue by TariqBlecher** [ratt-ru/CubiCal#105]
I ran two similar calibrations. 

The first with the min-bl=200. It gave terrible results.

The second after using CASA split, with uvrange>200 & keepflags =False. It gave good results.

So I think that the baselines with length less than 200 meters were problematic and that min-bl=200 did not ignore them properly.

**Comment by o-smirnov** [comment]
I did implement that feature rather quickly (and @IanHeywood had a problem with it), so it's possible that something ain't right still. Can you prepare an MS/parset demonstrating this problem?

Also, do note that there's a potential difference between your two scenarios. In the latter case, you've completely thrown out baselines <200m, both for cal and imaging. In the former case, ``-min-bl`` restricts what baselines the solver is run on, but the resulting solutions are *applied* to all baselines. To make the two scenarios comparable, you must then exclude short baselines from the imaging explicitly. But maybe you already did that?

**Comment by TariqBlecher** [comment]
Yup, can do. I left out the short baselines from both imaging steps

**Comment by o-smirnov** [comment]
I gotta say this works for me. Can you give me the MS, LSM, and parset? Also logfiles from both runs?

**Comment by o-smirnov** [comment]
Also, as a cross-check, a third way would be use ``--sel-taql`` to exclude baselines>200m from a cubical run completely (as opposed to only excluding them from a solve). Then compare the logfiles -- is the same number of rows being reported as being used? Are the solutions the same?

**Comment by o-smirnov** [comment]
Things make sense to me in the latest master. @TariqBlecher, @IanHeywood, could you please re-test and verify?

**Comment by o-smirnov** [comment]
@JSKenyon, if @TariqBlecher  can verify that this and #116 is solved, then feel free to push a release out...
