### ISSUE TITLE
I/O error - possible table lock related

### ISSUE THREAD

**Issue by TariqBlecher** [ratt-ru/CubiCal#106]
Anyone seen this crash report before? It may be due to a table locks? Will try casa's clearstat and rerun.

```
 - 16:25:35 - main               [0.3/0.3 3.0/3.1 19.4Gb] waiting for I/O on tile 2
 - 16:25:36 - main               [0.3/0.3 3.0/3.1 19.4Gb] Exiting with exception: AssertionError()
 Traceback (most recent call last):
  File "/vault-tina/blecher/J1106/3GC-cubical/CubiCalSrc/CubiCal/cubical/main.py", line 343, in main
    if not done or not io_futures[itile].result():
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 455, in result
    return self.__get_result()
  File "/home/blecher/cubical_venv/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
AssertionError


```

**Comment by o-smirnov** [comment]
I think I've seen this when I unwittingly have had a previous cubical run backgrounded, still accessing the same MS. So do check for that.

Also, can you reproduce the problem with ``--dist-ncpu 1``? This disables the multiprocessing, and can produce more revealing error messages.

**Comment by o-smirnov** [comment]
@TariqBlecher, is it reproducible?

**Comment by TariqBlecher** [comment]
Sorry I haven't seen this again. I think I have broken that particular MS by stopping the process at a sensitive point
