### ISSUE TITLE
remove dependency on astro-tigger

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#111]
Hurrah, the LSM reading code has been divorced from the Tigger GUI, and is now available standalone as ``astro-tigger-lsm`` on PyPI. No need to screw around with this vext crap. Adjust CubiCal dependency as appropriate.

**Comment by IanHeywood** [comment]
Does this affect any legacy Python scripts that use import Tigger?

**Comment by o-smirnov** [comment]
It shouldn't. The new ``astro-tigger-lsm`` package contains all the libraries that import Tigger pulls in, plus the various tigger-xxx command line utilities. It's just the viewer GUI that's been split out into a separate (upcoming) package.

**Comment by IanHeywood** [comment]
Nice!
