### ISSUE TITLE
A strange flagging comparison.

### ISSUE THREAD

**Issue by TariqBlecher** [ratt-ru/CubiCal#116]
Post G-Jones calibration, the corrected residual image is looking bad with a strong horizontal fringe running through the image. RMS ~ 55microJy.
![image](https://user-images.githubusercontent.com/10098269/34300112-44836c4e-e72f-11e7-9ee6-32abe8095f05.png)  

Then I reset the flags to Pre-Cubical flags and ran the same imaging command (i.e. imaging the corrected residual which cubical out). The RMS drops by 10 microJy. Inexplicably the fringe has now disappeared. 
![image](https://user-images.githubusercontent.com/10098269/34300156-7cb68452-e72f-11e7-8200-9b9062970dc0.png)
 
I wouldn't expect over-flagging to produce a huge fringe but maybe I am mistaken? There was no flagging for Gains Out Of Bounds but according to the Cubical log >3% visibility were flagged for chi2.

> - 15:08:48 - flagging           [0.3/0.4 3.0/3.1 0.0Gb] 10204 slots (0.98%) flagged on chi2 > 1.2*median
>  - 15:08:48 - flagging           [0.4/0.4 3.0/3.1 0.0Gb] 26291 more slots (2.54%) flagged on counts < 0.5*median
>  - 15:08:48 - flagging           [0.4/0.4 3.0/3.1 0.0Gb] 9 more channels flagged on density > 0.5
>  - 15:08:48 - flagging           [0.4/0.4 3.0/3.1 0.0Gb] 1 more timeslots flagged on density > 0.5
>  - 15:08:48 - flagging           [0.4/0.4 3.1/3.1 0.0Gb] 0 more ddids flagged on density > 0.5
>  - 15:08:49 - flagging           [0.4/0.4 3.5/3.5 0.0Gb] saved chi-sq flagging plot to cubical.chiflag.png
>  - 15:08:49 - stats              [0.4/0.4 3.5/3.5 0.0Gb] adjusting statistics based on output flags
>  - 15:08:49 - stats              [0.4/0.4 3.5/3.5 0.0Gb]   0.04% of all timeslots are flagged
>  - 15:08:49 - stats              [0.4/0.4 3.5/3.5 0.0Gb]   2.65% of all channels are flagged
>

**Comment by o-smirnov** [comment]
Good catch @TariqBlecher. This really seems paradoxical. MS and parset please?

**Comment by JSKenyon** [comment]
Out of interest, was this a fresh MS or one that you had used before? Sometimes things go awry if the bitflag column was wrecked on a previous run. That being said, it seems weird that it would cause a fringe.

**Comment by TariqBlecher** [comment]
Yeah I wasn't a fresh MS, but I did manually remove the BITFLAG and BITFLAG_ROW columns and I got the same result. I'll try it on a completely fresh MS though.

on tina: /home/blecher/SDSS1250-0135/2GC-split
MS : 8may-2GC-test.ms
parset : gain.parset

**Comment by TariqBlecher** [comment]
Just tried it on a fresh MS and the fringe appears.

**Comment by o-smirnov** [comment]
Can you retest please, @TariqBlecher (and provide me with a test MS if you still have problems?)

The current master has many fixes to flagging. In particular, visibility slots with bad G-Jones solutions are now properly flagged (hopefully). There is also some more output at the end of the run which explains exactly how much was flagged, and for which reasons.
