### ISSUE TITLE
simplify DDE options

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#128]
As per discussion with @JSKenyon:

* --model-ddes to be renamed to --model-force-ddes-off

* exit with error if jones terms specify a DDE, but model has no directions (as commonly happens when the user forgets a @dE tag)

**Comment by o-smirnov** [comment]
Hmmm, how about the following instead. @JSKenyon please consider it.

``--model-ddes never|auto|always``, default being "auto"

If there are no DD terms in the ones chain, then we can't have DDEs. If mode is "always", exit with error, otherwise evaluate the model without any directions.

If there **are** DD terms in the Jones chain:

* if mode is "never", we disable directions anyway 

* If mode is "auto", and the model specifies only one direction, exit with error (user probably forgot @dE tag)

* If mode is "always", proceed with DDE solution even if only one model direction is specified
 
So the basic philosophy is then, in mode "auto" we try to prevent the user from self-inflicted injuries, but in "alays" or "never", we assume they know what they're doing.

**Comment by JSKenyon** [comment]
This seems sensible. My main concern is ensuring that the user gets what they want most of the time. Your suggestion should save most people from themselves (myself included).
