### ISSUE TITLE
if --data-time-chunk or --data-freq-chunk is set to 0, use whole axis instead

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#129]
Requested by @IanHeywood. This is already the case for -time-int and -freq-int.

**Comment by JSKenyon** [comment]
This should be easy enough, though you take a massive performance hit.

**Comment by IanHeywood** [comment]
But if I want to use the entire frequency axis when generating a solution then there's no way around that, right?

**Comment by JSKenyon** [comment]
@IanHeywood Likely because I edited the comment. I realised too late that that was possibly the use-case you were thinking of. :-)
