### ISSUE TITLE
divergence in dE terms (caused by degenerate models?)

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#135]
This is an interesting one. Got a fix, but it feels like cooking -- probably @JSKenyon should make a note to chase down the real cause...

In the NGC4993 Jan 2018 observation, I have a G+dE solution run to completion, but generate some pretty wild visibilities. For reference, the command line:

```
gocubical cc-peel-dual.parset --sol-jones G,dE --data-ms avg-1ch10s.ms --data-column DATA --model-list MODEL_DATA:peeling.lsm.html@dE --out-subtract-dirs 1: --out-name cc-peel2c --out-column PEELED2C_DATA --g-solvable 1 --g-update-type phase-diag --data-time-chunk 40 --data-freq-chunk 512 --g-time-int 1 --g-freq-int 512 --de-time-int 5 --de-freq-int 128 --flags-apply legacy --flags-save peel --dist-ncpu 36 --out-mode ss --flags-tf-chisq-median 2 --weight-col WEIGHT_SPECTRUM --log-verbose main=1,data_handler=1,solver=3 --sol-term-iters 20,20,20 
```

In some chunks (D0T0F4 for example) this results in unreasonably large amplitudes. As I've established, what happens is that the dE solutions on some antennas (e.g. direction 1, time int 5, freq int 2 in this case) get slowly but progressively larger, hitting large values like 1e+13 at the iteration limit. The data is horribly overflagged, so it's quite possible that the solution is simply not well constrained -- or is the direction in a beam null so the model goes to zero? I haven't checked... So maybe there are no reasonable dE solutions at all -- but we need to catch this situation before it gets out of hand.

One would think flagging on posterior gain errors (i.e. the diagonal of the Hessian) would catch this, but no: these are reasonably small at the end of the iterations, where the code checks for them. Solution amplitude clipping would also catch this (it is off by default for dE's, but we could set it to e.g. 0.01 to 100 instead), but feels crude.

**Comment by o-smirnov** [comment]
So what seems to help (see commit above) is to flag on posterior_gain_error (i.e. the diagonal of the Hessian) on every iteration, rather than the final iteration. But, I have made the flagging reversible -- that is, if subsequent updates generate a reasonable Hessian, the solution is allowed to proceed.

Seems to work for now, but feels a little iffy. So I'd like to keep the issue open.

**Comment by IanHeywood** [comment]
```
we could set it to e.g. 0.01 to 100 instead
```

Out of interest, can you think of a scenario (woefully inappropriate sky models aside) where a dE amplitude deviating that far from unity would be legit?

**Comment by JSKenyon** [comment]
I think is ok to clip the dEs - I think that @IanHeywood hit the nail on the head. I would imagine any gain with such crazy amplitude is not to be trusted.

@o-smirnov I assume you were using beams? It is a known issue that Montblanc (assuming you are using it) doesn't do any clipping. Thus, sources can effectively become zero, leading to infinite gains.

**Comment by o-smirnov** [comment]
No question, such dE's are entirely non-legit and we're entitled to ignore them or flag them (not sure that a particular peeled source's dE going to 0 or infinity is reason to flag the timeslot though... if the data is not sensitive to that source at that point in time/freq, surely we should leave it alone? Which why the ``-prop-flags`` option is in there.)  I'm just disturbed by how slowly and elegantly this particular dE diverges (avoiding detection by the GNULL and ILLCOND checks). I had expected it to just blow up in an obvious way, but no, it blows up sneakily.

**Comment by JSKenyon** [comment]
I think the current behaviour (though it may have changed) is to simply set gains which hit the clip to identity. Admittedly, when I originally implemented it, it was not sophisticated. In truth, it might be interesting to lump sources which are behaving poorly with dEs back into direction 0. Not quite sure how we could accomplish that.

**Comment by o-smirnov** [comment]
> In truth, it might be interesting to lump sources which are behaving poorly with dEs back into direction 0

Setting their gains to unity accomplishes exactly that, in effect. 

There's nothing wrong with the clip behaviour -- it's a sensible backstop for when things really go south. I just have a nagging feeling that there should be a more elegant (and mathematically motivated) way to catch this situation before it hits the hard buffers.

**Comment by JSKenyon** [comment]
Absolutely - it is quite tricky. I am a little bit surprised that your existing checks didn't pick it up.  If it was a source in the null, then I guess an infinite gain is technically "correct". Maybe that undermines the current checks?
