### ISSUE TITLE
BITFLAG bail out but really it's fine

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/CubiCal#141]
Running CubiCal (master branch, updated yesterday) on some ASKAP data, I get a crash as follows:

```
 - 11:38:10 - data_handler       [0.1/0.1 0.9/0.9 0.1Gb]   Will auto-fill new BITFLAG 'legacy' (1) from FLAG/FLAG_ROW
 - 11:38:10 - data_handler       [0.1/0.1 0.9/0.9 0.1Gb]     BITFLAG column defines the following flagsets: legacy:1
 - 11:38:10 - data_handler       [0.1/0.1 0.9/0.9 0.1Gb]     Applying flagset(s) legacy
 - 11:38:10 - data_handler       [0.1/0.1 0.9/0.9 0.1Gb]   Applying BITFLAG mask 1 to input data
 - 11:38:10 - main               [0.1/0.1 0.9/0.9 0.1Gb] Exiting with exception: RuntimeError(NullTable::getColumn - 
Table object is empty)
 Traceback (most recent call last):
  File "/mnt/home/ianh/Software_M/CubiCal/cubical/main.py", line 244, in main
    max_baseline=GD["sol"]["max-bl"])
  File "/mnt/home/ianh/Software_M/CubiCal/cubical/data_handler.py", line 1224, in __init__
    self._save_bitflag = bitflags.flagmask(save_bitflag, create=True)
  File "/mnt/home/ianh/Software_M/CubiCal/cubical/flagging.py", line 158, in flagmask
    self.ms._putkeyword('BITFLAG','FLAGSETS',-1,False,','.join(self.order))
RuntimeError: NullTable::getColumn - Table object is empty
```

But then when I run it again it happily proceeds. Anything obvious I can look at to figure out why? Not the end of the world, but not great if I want to put this into a pipeline...

**Comment by JSKenyon** [comment]
This looks like our dear friend the BITFLAG column at work again. Would you mind copy pasting the [flag] section of your parset here? @o-smirnov Is more likely to know off the top of his head what went wrong, put I can take a look.

**Comment by JSKenyon** [comment]
I am really uncertain. It looks like pyrap suddenly believes that the underlying table is empty. I could understand a second run fixing that if `reinit-bitflags` was enabled, but this seems a little more peculiar.

**Comment by o-smirnov** [comment]
Duh, sorry -- that was me trying to fix something else, and breaking this subtly. Somewhere along the way, I must've picked up a curse. I am doomed to an eternity of breaking and fixing bitflags, in a futile and useless cycle of commits and PRs.

@IanHeywood, could you please check if the ``issue-141`` branch makes the problem go away?

**Comment by IanHeywood** [comment]
OK will check when some stuff I'm working on reaches a suitable point to stop. Can also confirm the problem occurs with a MeerKAT MS.

**Comment by o-smirnov** [comment]
OK, I was just bitten by this myself. But can also confirm that my fix works, so will issue a PR shortly (fixing a few other minor issues).
