### ISSUE TITLE
issue a release?

### ISSUE THREAD

**Issue by gijzelaerr** [ratt-ru/CubiCal#145]
We want to use features from a more recent version of CubiCal than 0.9.2. Can you make a new release, please?

:)

**Comment by o-smirnov** [comment]
Fine by me, we don't have any major PRs outstanding. But I'd still check with @TariqBlecher if #105 has been solved for him. Or just release, and make another point release later if needed.

**Comment by JSKenyon** [comment]
Done. Bumped to version 1.0.0 and there is an sdist available on pypi.
