### ISSUE TITLE
doubled memory use in Montblanc mode

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#147]
I'm seeing a lot of memory use when using Montblanc for predict. Compare these two log snippets. In the first case, I specify 10 directions via visibility columns:

``` - 21:30:25 - data_handler       [0.3/0.3 2.7/2.9 0.2Gb] tile #1/4: reading MS rows 0~273596
 - 21:30:26 - data_handler       [2.3/2.3 16.3/16.3 1.3Gb]   reading MODEL_DATA for model 0 direction 0
 - 21:30:35 - data_handler       [14.4/14.4 16.8/17.3 12.8Gb] (11, 1, 273597, 64, 4)
 - 21:30:37 - data_handler       [15.7/15.9 19.2/19.5 13.4Gb]   17.82% input visibilities flagged and/or deselected
 - 21:30:50 - solver             [3.9/15.9 6.4/19.5 13.4Gb] D0T0F0 G: 9 iters, conv 100.00%, d/fl 35.71%, PGE 0.000922; dE: 1 iters, conv 100.00%, d/fl 14.29%, PGE 0.000198 0.000198 0.000198 0.000198 0.000198 0.000198 0.000198 0.000198 0.000198 0.000198 0.000198; G: 1 iters, conv 100.00%, d/fl 35.71%, PGE 0.000922, stall 0.00%, chi^2 922.6 -> 0.1406 (1.338), noise 25.5 -> 2.22
 - 21:30:51 - data_handler       [0.5/15.9 3.0/19.5 13.5Gb] tile #1/4: saving MS rows 0~273596
 - 21:30:51 - data_handler       [0.5/15.9 3.0/19.5 13.5Gb]   writing CORRECTED_DATA column
 - 21:30:52 - data_handler       [1.6/15.9 4.0/19.5 14.5Gb]   no new flags generated
```

(The numbers in the brackets are, current/max resident, current/max virtual, and shared memory use, in Gb). So you can see the memory footprint jump to ~16GB as data is read in -- and the ~13.5Gb shared memory (NB: I'm not sure if the shared memory is counted as part of resident memory?), where the 10x direction model array lives, is the biggest memory hog. The solver's own RAM impact, on top of that, is surprisingly gentle.

Now a similar run using Montblanc, with a 10-direction model:

```
  - 21:33:53 - data_handler       [0.3/0.3 2.8/2.9 0.2Gb] tile #1/4: reading MS rows 0~273596
 - 21:34:02 - data_handler       [2.4/2.5 15.3/15.4 1.3Gb]   computing visibilities for 3C147-dE-apparent.lsm.html
2018-04-12 21:34:04.138241: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
 - 21:34:34 - data_handler       [27.9/37.3 50.4/59.8 11.7Gb] (10, 1, 273597, 64, 4)
 - 21:34:36 - data_handler       [29.3/37.3 52.8/59.8 12.4Gb]   17.82% input visibilities flagged and/or deselected
 - 21:35:25 - solver             [17.8/37.3 40.3/59.8 12.4Gb] D0T0F0 G: 8 iters, conv 100.00%, d/fl 35.71%, PGE 0.000624; dE: 20 iters, conv 20.00%, d/fl 14.29%, PGE 1.23e-05 0.00891 0.0138 0.0214 0.0142 0.031 0.0539 0.0682 0.0 0.0; G: 4 iters, conv 100.00%, d/fl 35.71%, PGE 0.000624, stall 32.86%, chi^2 11.15 -> 0.117 (1.154), noise 25.5 -> 2.21
 - 21:35:26 - data_handler       [14.7/37.3 37.2/59.8 12.5Gb] tile #1/4: saving MS rows 0~273596
 - 21:35:26 - data_handler       [14.7/37.3 37.2/59.8 12.5Gb]   writing CORRECTED_DATA column
 - 21:35:27 - data_handler       [15.7/37.3 38.2/59.8 13.4Gb]   no new flags generated
 ```

Boom, a ~13Gb memory hit, which is suspiciously close to the total model visibility size. So it's almost like Montblanc (or the CubiCal interface to it) is hanging on to an extra copy of the per-direction model visibilities. This should not be necessary -- after the predict is done, there should be a way to clear all internals -- so let's find it and burn it.

(Important, because we're already hitting the RAM buffers with MeerKAT data...)

**Comment by JSKenyon** [comment]
I wonder if this happens because we reuse the same solver instance? If that is the case, the problem is probably [here](https://github.com/ratt-ru/CubiCal/blob/3ddb727c64a8577b04403977cbfadf15afd3cdbe/cubical/MBTiggerSim.py#L223). Problem might not be the correct terminology though. It is possible to create a new solver on each predict (that was the original behaviour) but I think we found that there were overheads. @sjperkins Any thoughts?

**Comment by o-smirnov** [comment]
> If that is the case, the problem is probably here. 

An excellent guess -- that's exactly where a memory profiling run points. We don't need a new solver if @sjperkins can tell the old one to drop its buffers...

**Comment by sjperkins** [comment]
Internally, the solver maintains a tensorflow Session (possible culprit) and threadpool, which the `close` method shuts down.

However, I think the tensorflow Session is unlikely. See attached script which runs the solver 10000 times (default data is generated for each run) and see what happens when you run it in your virtual environment:

[standalone.zip](https://github.com/ratt-ru/CubiCal/files/1906298/standalone.zip)

Memory usage stays constant on my machine (Montblanc master branch). So try bring the solver up and down on each iteration, but I doubt that's the issue.

Try calling the `cache_size` method on the CachedSourceProvider instances?

**Comment by sjperkins** [comment]
Here's a version of [standalone.zip](https://github.com/ratt-ru/CubiCal/files/1907385/standalone.zip) profiled with [pympler](https://pythonhosted.org/Pympler) and the following command

`python  standalone.py --ntime 10000 --na 64 --nchan 4096`

which is a fairly large problem space (ran it on my GPU). pympler thinks that memory usage is ~25MB before creating a solver and ~62MB after running it 10 times and closing it. Total object counts number around ~62MB between solutions. While there are some dicts and strings hanging around this tells me that tensorflow and Montblanc do not hold data and clean up after themselves.

```bash
                                     types |   # objects |   total size
========================================== | =========== | ============
                                      dict |        8958 |      9.08 MB
                                       str |       37046 |      4.75 MB
                                      code |       14134 |      1.73 MB
                                      type |        1855 |      1.61 MB
                                   unicode |        5757 |      1.27 MB
                                      list |       12764 |      1.26 MB
                                       set |        1369 |    605.16 KB
                                     tuple |        6634 |    485.95 KB
                                   weakref |        3730 |    320.55 KB
                        wrapper_descriptor |        2371 |    185.23 KB
  <class 'astropy.units.core.CompositeUnit |        2343 |    146.44 KB
                       function (__init__) |        1014 |    118.83 KB
                         getset_descriptor |        1518 |    106.73 KB
                          _sre.SRE_Pattern |         208 |    101.31 KB
                builtin_function_or_method |        1404 |     98.72 KB
Total object memory usage 24.8MB
                                                types |   # objects |   total size
===================================================== | =========== | ============
                                                 dict |       17046 |     17.83 MB
                                                  str |      150249 |     17.15 MB
                                                 list |       49605 |      5.43 MB
                                                 code |       32222 |      3.93 MB
                                                 type |        3698 |      3.20 MB
                                              unicode |        9754 |      2.31 MB
                                                tuple |       22571 |      1.86 MB
                                                  set |        2014 |    909.55 KB
                                              weakref |        6483 |    557.13 KB
                                                  int |       18635 |    436.76 KB
  <class 'tensorflow.core.framework.op_def_pb2.ArgDef |        2600 |    304.69 KB
                           builtin_function_or_method |        3720 |    261.56 KB
                                  function (__init__) |        2214 |    259.45 KB
                                                 cell |        4320 |    236.25 KB
                                             property |        2670 |    229.45 KB
Total object memory usage 62.2MB
```

**Comment by o-smirnov** [comment]
> While there are some dicts and strings hanging around this tells me that tensorflow and Montblanc do not hold data

Au contraire, I read it as there's 37GB extra hanging around after you're done with the solver, right? That's exactly the problem -- we need the RAM footprint to drop back down to pre-solver sizes after the solver is done, but it's not happening....

**Comment by sjperkins** [comment]
This is likely the large allocation:

https://github.com/ratt-ru/CubiCal/blob/master/cubical/data_handler.py#L382-L384

But it gets put in objects which don't survive the function scope

But here it gets sliced and put in a dict, then re-extracted from a dict.

https://github.com/ratt-ru/CubiCal/blob/master/cubical/data_handler.py#L392-L403

Perhaps slicing the large parent array returns a view which is then kept around due to the reference?
Does this mean that the parent array is never deallocated?

**Comment by sjperkins** [comment]
Also, would it not be possible to simple run this on ray or stevie, which have plenty of RAM, rather than the venerable astronomer's laptop, which, while indispensable, does not always have the firepower...

**Comment by o-smirnov** [comment]
Well the dict with the views is deleted here: https://github.com/ratt-ru/CubiCal/blob/master/cubical/data_handler.py#L405

The only other thing done with the views is a += (into the shared memory array) at https://github.com/ratt-ru/CubiCal/blob/master/cubical/data_handler.py#L403, which won't increment the refcount...

So indeed once the function scope is done, I don't expect any of this to hang around.

**Comment by sjperkins** [comment]
Out of left-field, but, python has a generational garbage collector (younger objects are culled first, while older objects are viewed as likely to hang around).

How about a judicious `gc.collect()` to see if this is maybe this case?

```python
import gc

...
gc.collect()
```

**Comment by sjperkins** [comment]
> How about a judicious gc.collect() to see if this is maybe this case?

In the sense that the predict takes a while, pushing the `full_model` variable into the older generation...

`gc.collect()` will clear all generations.

**Comment by sjperkins** [comment]
Interestingly, from [wikipedia](https://en.wikipedia.org/wiki/Tracing_garbage_collection#Generational_GC_(ephemeral_GC)), garbage collectors have major and minor cycles too:

> ; for example, most collection cycles might look only at a few generations, while occasionally a mark-and-sweep is performed, and even more rarely a full copying is performed to combat fragmentation. The terms "minor cycle" and "major cycle" are sometimes used to describe these different levels of collector aggression.

**Comment by o-smirnov** [comment]
Interesting... ok, I'll poke around over the weekend... if you have more ideas, do share.

**Comment by JSKenyon** [comment]
@o-smirnov Not sure what you have and haven't tried yet. Can you try replacing the simulate function with the following? 

```
def simulate(src_provs, snk_provs, opts):
    """
    Convenience function which creates and executes a Montblanc solver for the given source and 
    sink providers.
    Args:
        src_provs (list): 
            List of :obj:`~montblanc.impl.rime.tensorflow.sources.SourceProvider` objects. See
            Montblanc's documentation.
        snk_provs (list):
            List of :obj:`~montblanc.impl.rime.tensorflow.sinks.SinkProvider` objects. See
            Montblanc's documentation. 
        opts (dict):
            Montblanc simulation options (see [montblanc] section in DefaultParset.cfg).
    """
    slvr_cfg = montblanc.rime_solver_cfg(
            mem_budget=opts["mem-budget"]*1024*1024,
            dtype=opts["dtype"],
            polarisation_type=opts["feed-type"],
            device_type=opts["device-type"])

     _mb_slvr = montblanc.rime_solver(slvr_cfg)
        
    _mb_slvr.solve(source_providers=src_provs, sink_providers=snk_provs)
```

**Comment by sjperkins** [comment]
I would suggest putting it in a `with` block to force a call to the solver's `call()` method

```
def simulate(src_provs, snk_provs, opts):
    """
    Convenience function which creates and executes a Montblanc solver for the given source and 
    sink providers.
    Args:
        src_provs (list): 
            List of :obj:`~montblanc.impl.rime.tensorflow.sources.SourceProvider` objects. See
            Montblanc's documentation.
        snk_provs (list):
            List of :obj:`~montblanc.impl.rime.tensorflow.sinks.SinkProvider` objects. See
            Montblanc's documentation. 
        opts (dict):
            Montblanc simulation options (see [montblanc] section in DefaultParset.cfg).
    """
    slvr_cfg = montblanc.rime_solver_cfg(
            mem_budget=opts["mem-budget"]*1024*1024,
            dtype=opts["dtype"],
            polarisation_type=opts["feed-type"],
            device_type=opts["device-type"])

    with montblanc.rime_solver(slvr_cfg) as slvr:
        slvr.solve(source_providers=src_provs, sink_providers=snk_provs)
```

**Comment by o-smirnov** [comment]
> Also, would it not be possible to simple run this on ray or stevie, which have plenty of RAM, rather than the venerable astronomer's laptop, which, while indispensable, does not always have the firepower...

Ah but that's exactly the crux of it -- we've already driven it into regimes where even a stevie runs of of RAM! With full MeerKAT, this will be routine. So a factor of 2 is a big deal (and actually makes that paper @JSKenyon reviewed more interesting... hmmm, will their "burn the model" work if we do diagonal-only DDEs?)

**Comment by o-smirnov** [comment]
> How about a judicious gc.collect() to see if this is maybe this case?

Bingo! Congratulations on your very educated guess, @sjperkins. Adding a ``gc.collect()`` (after the ``del loaded_models`` statement [here](https://github.com/ratt-ru/CubiCal/blob/master/cubical/data_handler.py#L405)) dropped the footprint right back down.

**Comment by sjperkins** [comment]
One thing you should also be aware of is that the garbage collector handles reference cycles (two objects reference each other so neither gets collected), while the reference counting collector does not. So there may have been a reference cycle somewhere in the above code which `gc.collect()` resolves.

This article https://rushter.com/blog/python-garbage-collector/ describes the situation for python 3.6 and I'd imagine it would be the same for python 2.7
