### ISSUE TITLE
Write out CASA-style gaintables

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#160]
Stay tuned... this should make life much easier in terms of getting diagnostics out of cubical.

**Comment by bennahugo** [comment]
@o-smirnov this is almost done however I'm confused about the tables that are being dumped in f-slope mode:
- there is a gain table and a phase table. From what I can see the gain table contains the diagonal re&im components for the phases stored in the phase table.  I presume this is just the constant offset "c" in the expression a\nu + bt + c and that you are essentially solving for KG Jones?
- The cable delay (K) is therefore "a" but when I solve this on my a subset of DEEP2 data and with the brightest components then I get numbers of the sub-second magnitude out. The data is already delay calibrated, so these numbers should be sub-nanosecond level
[[[[[-0.540511965751648 -0.19621838629245758]
    [0.07305947691202164 0.17716243863105774]
    [nan nan]
    ...
    [0.22916153073310852 0.05532080680131912]
    [-0.17053945362567902 0.29136112332344055]
    [-0.10271869599819183 -0.19864095747470856]]]

**Comment by bennahugo** [comment]
Yup so the norm term is divide by solution bandwidth:
```
[[[[[-0.631439208984375 -0.22922708094120026]
    [0.08534985780715942 0.20696547627449036]
    [-- --]
    ...
    [0.2677120864391327 0.06462711095809937]
    [-0.19922833144664764 0.340375155210495]
    [-0.11999848484992981 -0.23205719888210297]]]
```
the following needs to be added to the G phase term:
-(a\nu_low)/(\nu_bandwidth)

**Comment by o-smirnov** [comment]
This has gone in I think, thanks @bennahugo.
