### ISSUE TITLE
setup.py does not rebuild cython kernels when updating master

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/CubiCal#180]
This is a new one... Any ideas? It's a fresh MeerKAT MS, using the master branch.

```
 - 01:11:14 - data_handler       [0.5/0.5 3.5/3.5 48.7Gb] tile #1/58: reading MS rows 0~95039
 - 01:11:53 - data_handler       [23.7/23.7 38.3/38.3 60.3Gb]   reading MODEL_DATA for model 0 direction 0
 - 01:12:46 - data_handler       [59.9/61.4 77.5/79.0 77.7Gb]   applying solvable baseline cutoff deselects 0 rows
 - 01:12:47 - data_handler       [59.9/61.4 77.5/79.0 77.7Gb]   error reading BITFLAG column: not fatal, since we'll auto-fill it from FLAG
 - 01:12:47 - data_handler       [59.9/61.4 77.5/79.0 77.7Gb]     Traceback (most recent call last):
 - 01:12:47 - data_handler       [59.9/61.4 77.5/79.0 77.7Gb]       File "/home/ianh/Software/CubiCal/cubical/data_handler.py", line 494, in load
 - 01:12:47 - data_handler       [59.9/61.4 77.5/79.0 77.7Gb]         self.bflagcol = self.handler.fetchslice("BITFLAG", self.first_row, nrows)
 - 01:12:47 - data_handler       [59.9/61.4 77.5/79.0 77.7Gb]       File "/home/ianh/Software/CubiCal/cubical/data_handler.py", line 1494, in fet
chslice
 - 01:12:47 - data_handler       [59.9/61.4 77.5/79.0 77.7Gb]         return self.data.getcol(column, startrow, nrows)
 - 01:12:47 - data_handler       [59.9/61.4 77.5/79.0 77.7Gb]       File "/home/ianh/venv/meerkat/local/lib/python2.7/site-packages/casacore/tabl
es/table.py", line 1006, in getcol
 - 01:12:47 - data_handler       [59.9/61.4 77.5/79.0 77.7Gb]         return self._getcol(columnname, startrow, nrow, rowincr)
 - 01:12:47 - data_handler       [59.9/61.4 77.5/79.0 77.7Gb]     RuntimeError: Table DataManager error: Invalid operation: TSM: no array in row
0 of column BITFLAG in /home/ianh/MIGHTEE/COSMOS_COMBINED/1523464709_sdp_l0.full_pol_fg_wtspec_COSMOS.ms/table.f25
 - 01:12:49 - data_handler       [65.7/65.7 83.3/83.3 77.7Gb]   auto-filling BITFLAG/BITFLAG_ROW of shape (95040, 4096, 4)
 - 01:13:05 - data_handler       [70.1/74.4 84.8/92.0 80.6Gb]   31.42% input visibilities flagged and/or deselected
 - 01:13:06 - solver             [6.3/74.4 9.3/92.0 80.6Gb] Solver for tile 0 chunk D0T0F0 failed with exception: 'module' object has no attribut
e 'allocate_vis_array'
 - 01:13:06 - solver             [6.3/74.4 9.3/92.0 80.6Gb] Traceback (most recent call last):
  File "/home/ianh/Software/CubiCal/cubical/solver.py", line 689, in run_solver
    allocator=kernel.allocate_vis_array,
AttributeError: 'module' object has no attribute 'allocate_vis_array'
 - 01:13:06 - main               [6.3/74.4 9.3/92.0 80.6Gb] Exiting with exception: AttributeError('module' object has no attribute 'allocate_vis
_array')
 Traceback (most recent call last):
  File "/home/ianh/Software/CubiCal/cubical/main.py", line 352, in main
    stats_dict = workers.run_process_loop(ms, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/home/ianh/Software/CubiCal/cubical/workers.py", line 203, in run_process_loop
    return _run_single_process_loop(ms, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/home/ianh/Software/CubiCal/cubical/workers.py", line 316, in _run_single_process_loop
    solver.run_solver(solver_type, itile, key, solver_opts, debug_opts)
  File "/home/ianh/Software/CubiCal/cubical/solver.py", line 689, in run_solver
    allocator=kernel.allocate_vis_array,
AttributeError: 'module' object has no attribute 'allocate_vis_array'
```

**Comment by JSKenyon** [comment]
Pretty sure this is the same issue. Because we are no longer including the cythonsied files, everything needs to be cythonsied and compiled during the install process. The hack for this is to pip install cython into your environment before doing the install. You can probably fix it with a `pip install cython` and a `pip install -U -e CubiCal/`. You can add --user if needed, though I prefer using virtualenvs.

**Comment by IanHeywood** [comment]
But this is running master in a virtualenv on nash, a setup which I haven't modified for at least several days... All my other woes were with issue-151 branch on the IDIA machines.

Tear everything down and start again?

**Comment by JSKenyon** [comment]
A large update went into master 4 days ago. That is where the change comes from. SO if you have updated you master at all since then, you will see the problem.

**Comment by o-smirnov** [comment]
*"All of this has happened before and all of this will happen again..."*

@IanHeywood, you pulled in the latest master and this produced the error, right? This is a problem with the build system that we've seen before, sometimes it doesn't pick up that the Cython kernels have been updated, and therefore doesn't rebuild them. 

You do need to 

* ``pip install cython`` in the virtualenv (I've just added it to setup.py in the latest commit on my branch, so it will be installed for you in the future... @JSKenyon we should probably push this fix to master too asap, as the build is broken as things stand.)

* ``rm cubical/kernels/*.{c,cpp}``, just to make sure it makes fresh versions

* ``pip install -e CubiCal/``

The last spate of commits to master changed quite a few things in the kernels and the build system, so hopefully this is just transition pains.

**Comment by o-smirnov** [comment]
P.S. I have renamed the issue to reference the underlying cause. Adding cython to the requirements will probably fix it, but I'd still like an "clean build" command for the future...

**Comment by IanHeywood** [comment]
OK I have it running again on nash, but not trying any on-the-fly averaging yet. Progress of sorts on IDIA, please see issue #151

**Comment by ulricharmel** [comment]
Hi @o-smirnov , @JSKenyon , I don't know if the issue I am getting is exactly this one. I have pulled amd merge the latest release but then I am getting errors reinstalling cubical. I work in a virtual environment on jake (myenv) and my cubical code is on elwood (/net/elwood/home/ulrich/cubenv/CubiCal).
When I run **python setup,py develop** 

 (myenv) ulrich@jake:/net/elwood/home/ulrich/cubenv/CubiCal$ python setup.py develop
running develop
running egg_info
writing requirements to cubical.egg-info/requires.txt
writing cubical.egg-info/PKG-INFO
writing top-level names to cubical.egg-info/top_level.txt
writing dependency_links to cubical.egg-info/dependency_links.txt
writing entry points to cubical.egg-info/entry_points.txt
reading manifest file 'cubical.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'cython'
writing manifest file 'cubical.egg-info/SOURCES.txt'
running build_ext
building 'cubical.kernels.cygenerics' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/ulrich/myenv/local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c cubical/kernels/cygenerics.c -o build/temp.linux-x86_64-2.7/cubical/kernels/cygenerics.o -ffast-math -O2 -march=native -mtune=native -ftree-vectorize
x86_64-linux-gnu-gcc: error: cubical/kernels/cygenerics.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Then if I try reinstall from fresh by running **pip install -I CubiCal**
(myenv) ulrich@jake:/net/elwood/home/ulrich/cubenv$ pip install -I -e CubiCal
Obtaining file:///net/elwood/home/ulrich/cubenv/CubiCal
Collecting numpy (from cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/6a/a9/c01a2d5f7b045f508c8cefef3b079fe8c413d05498ca0ae877cffa230564/numpy-1.14.5-cp27-cp27mu-manylinux1_x86_64.whl
Collecting futures (from cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Collecting python-casacore>=2.1.2 (from cubical==1.2.1)
Collecting sharedarray (from cubical==1.2.1)
Collecting matplotlib (from cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/33/da/6409d32c46778ed20308e83bc501ff2ff8a9cbda5dd7b26362c5e99a6149/matplotlib-2.2.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cython (from cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/ae/02/4f218b527aee1a1ea5592ec2f75052f6dbc616f6107a1c7658f92ae19962/Cython-0.28.4-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scipy (from cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/2a/f3/de9c1bd16311982711209edaa8c6caa962db30ebb6a8cc6f1dcd2d3ef616/scipy-1.1.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting astro-tigger-lsm (from cubical==1.2.1)
Collecting argparse (from python-casacore>=2.1.2->cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib->cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting backports.functools-lru-cache (from matplotlib->cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting subprocess32 (from matplotlib->cubical==1.2.1)
Collecting pytz (from matplotlib->cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl
Collecting six>=1.10 (from matplotlib->cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from matplotlib->cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib->cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/3a/62/a8c9bef3059d55ab38e41fe9cba4fad773bfc04e47290bab84db1c18262e/kiwisolver-1.0.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting cycler>=0.10 (from matplotlib->cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting astro-kittens (from astro-tigger-lsm->cubical==1.2.1)
Collecting astlib (from astro-tigger-lsm->cubical==1.2.1)
Collecting pyfits (from astro-tigger-lsm->cubical==1.2.1)
Collecting setuptools (from kiwisolver>=1.0.1->matplotlib->cubical==1.2.1)
  Using cached https://files.pythonhosted.org/packages/ff/f4/385715ccc461885f3cedf57a41ae3c12b5fec3f35cce4c8706b1a112a133/setuptools-40.0.0-py2.py3-none-any.whl
rfimasker 1.0.1 has requirement python-casacore==2.1.2, but you'll have python-casacore 2.2.1 which is incompatible.
Installing collected packages: numpy, futures, argparse, python-casacore, sharedarray, pyparsing, backports.functools-lru-cache, subprocess32, pytz, six, python-dateutil, setuptools, kiwisolver, cycler, matplotlib, cython, scipy, astro-kittens, astlib, pyfits, astro-tigger-lsm, cubical
  Found existing installation: cubical 1.2.1
    Uninstalling cubical-1.2.1:
      Successfully uninstalled cubical-1.2.1
  Running setup.py develop for cubical
    Complete output from command /home/ulrich/myenv/bin/python2 -c "import setuptools, tokenize;__file__='/net/elwood/home/ulrich/cubenv/CubiCal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing requirements to cubical.egg-info/requires.txt
    writing cubical.egg-info/PKG-INFO
    writing top-level names to cubical.egg-info/top_level.txt
    writing dependency_links to cubical.egg-info/dependency_links.txt
    writing entry points to cubical.egg-info/entry_points.txt
    reading manifest file 'cubical.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'cython'
    writing manifest file 'cubical.egg-info/SOURCES.txt'
    running build_ext
    building 'cubical.kernels.cygenerics' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/ulrich/myenv/local/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c cubical/kernels/cygenerics.c -o build/temp.linux-x86_64-2.7/cubical/kernels/cygenerics.o -ffast-math -O2 -march=native -mtune=native -ftree-vectorize
    x86_64-linux-gnu-gcc: error: cubical/kernels/cygenerics.c: No such file or directory
    x86_64-linux-gnu-gcc: fatal error: no input files
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of cubical
Command "/home/ulrich/myenv/bin/python2 -c "import setuptools, tokenize;__file__='/net/elwood/home/ulrich/cubenv/CubiCal/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /net/elwood/home/ulrich/cubenv/CubiCal/

**Comment by o-smirnov** [comment]
There's an extra ``python setup.py gocythonize`` step that @JSKenyon added. Having the kernels cythonized automatically was producing some undesirable behaviour, as I remember... anyway he can point you to the exact sequence needed....

**Comment by JSKenyon** [comment]
@ulricharmel [Follow these instructions](http://cubical.readthedocs.io/en/latest/installation.html). Actually, going to go ahead and close this as it has now been addressed. For anyone finding this issue, please make sure to read the docs for the new instructions for developers. Users are encouraged to install from PyPI.
