### ISSUE TITLE
Debian and git-lfs

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/CubiCal#185]
From Slack:

"about cubical, that .gitattribute file is also causing troubles.
maybe we should add a `.gitattributes export-ignore` inside the `.gitatributes` file
you guys use the lfs module for git, and now debian also tries to import that during packaging"

**Comment by JSKenyon** [comment]
Assigning @o-smirnov as I am not super familiar with git lfs or the suffering that changes may bring.

**Comment by gijzelaerr** [comment]
just adding and checking if .gitattributes is not in an export/release would be enough.

until then I can't add cubical to KERN (-dev/4)
