### ISSUE TITLE
FLAG ignored when BITFLAGs are read / unexpected null BITFLAGs

### ISSUE THREAD

**Issue by rvweeren** [ratt-ru/CubiCal#186]
Cubical cannot find solutions giving these sorts of warnings:
(problem remains with higher --g-time-int, --g-max-prior-error 0 --g-max-post-error 0 also does not help)

 - 16:12:17 - solver             [x26] [2.6/2.6 3.5/5.0 4.7Gb] D0T111F0 no solutions: G: 0/100 ints; flags LOWSNR:768800(100.00%) MISSING:12400(1.61%)

Command used:

gocubical --data-ms L232877_SB344_uv.dppp.pre-cal_124B2FCD4t_140MHz.pre-cal.ms --out-mode sc --g-time-int 1 --g-freq-int 2 --data-time-chunk 10 --data-freq-chunk 0 --data-column CORRECTED_DATA --model-list DD_PREDICT --out-column DATA_DI_CORRECTED --dist-ncpu 56 --weight-column None --out-casa-gaintables 0 --flags-save None --out-name L232877_SB344_uv.dppp.pre-cal_124B2FCD4t_140MHz.pre-cal.ms/CubiCal_DIS0 --log-verbose solver=2

Data can be found here: ftp://ftp.strw.leidenuniv.nl/pub/vanweeren/cubicalissue.tar.gz

We are using branch lofar-may2018 in Leiden

**Comment by rvweeren** [comment]
Link was not working, here is is again 

ftp://ftp.strw.leidenuniv.nl/pub/vanweeren/cubicalissue.tar.gz

**Comment by o-smirnov** [comment]
Well, I can confirm I can reproduce it on your MS.... looking into it.

**Comment by o-smirnov** [comment]
OK, it wasn't reading flags properly, so ended up with some really high values from the DATA column, which skewered the noise estimates. Workaround is to set ``--flags-reinit-bitflag 1``. I get solutions then.

I think the way you're using it in the pipeline is contradicting CubiCal's current flagging philosophy. Maybe the answer is to add some options to allow you to use flags your way...

**Comment by o-smirnov** [comment]
I will add some options to allow one to completely ignore bitflags and just use the standard FLAG column for input (in which case there's no way for the solver to **output** error conditions such as bad solutions etc., but that's another problem for another day).

I think I can also guess what the failure mode of @rvweeren was:

* start cubical on an MS without bitflags -- cubical inserts a BITFLAG column and proceeds to auto-fill it from FLAG

* interrupt proceedings at just the wrong time (column inserted but not yet filled)

* next run, cubical sees BITFLAG and proceeds to read it in preference to FLAG -- but it is empty

I think there's a robust way to avoid this which I can easily implement:

* when creating a bitflag column, set a special column keyword, e.g. "FILLING=True"

* once the column is successfully filled, clear the keyword

* when reading an MS whose bitflag column has FILLING=True set, assume the column is in an incomplete state from a previously interrupted run, and must be reinitialized before use
