### ISSUE TITLE
rebase your branches please

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#190]
(Sorry for abusing the issue mechanism, but I can't figure out how else to broadcast to @all.)

I have forced-push a modification to the repo to eradicate some large files I accidentally checked in. If you have any branches you're working on, you're going to need to rebase your branches. Otherwise, easiest thing to do is to wipe your local copy of the repo, and git clone it again.

**Comment by JSKenyon** [comment]
Has this actually happened already?

**Comment by o-smirnov** [comment]
Yes sorry. After many failed attempts, I pulled the trigger too early.

**Comment by ulricharmel** [comment]
Hi @o-smirnov  I can't see any new commit (the one forced push). Do you mean git clone will clone something different from what we are seeing here?

**Comment by o-smirnov** [comment]
Yes. You need to git fetch origin to get the new repo version. 

My rebase-fu is not up to scratch, but I'm guessing that if your branch didn't touch any of the files that I purged, then it should be a no-op.
