### ISSUE TITLE
Cubical chi-square plots

### ISSUE THREAD

**Issue by KshitijT** [ratt-ru/CubiCal#195]
The labels of Chi-sq {by antenna, by channel} plots are swapped. I don't know if this is only in madmax or in master too. 

Also, more ticks on the antenna axis would be great, especially for data with large number of antennas, right now it is a bit troublesome to find an errant antenna.

**Comment by KshitijT** [comment]
Ah. Makes sense now. Thanks for clarifying.

**Comment by o-smirnov** [comment]
Is this a better plot?

![image](https://user-images.githubusercontent.com/6470079/41907120-34ec72d2-7940-11e8-8c53-3b915ca6af3d.png)

BTW, you're pretty good at matplotlib yourself, so feel free to contribute improvements... the current code was never meant to be the be-all and end-all of plotting.
