### ISSUE TITLE
Apply parallactic angle corrections to MODEL_DATA

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#207]
It would be quite nice if it would be possible to turn parallactic angle correction for MODEL_DATA.

Workflow is as follows
- CASA setjy to predict basic (polarized) calibrator models to MODEL_DATA.
- Solve and apply bandpass using cubical which needs to solve parallactic angle on the fly.

As far as I can see this is simply a rotation matrix (Hales, 5) in the linear case and a diagonal exponential (Hales, 6) 

Another thing that I just realized is that our starting angles are off by a full 90deg - may explain why the MK beam corrections aren't quite working. This trick is generally necessary in CASA to get the polcal to behave:
```
    def __correct_feed_convention(ms):
        from pyrap.tables import table as tbl
        import numpy as np
        with tbl("%s::FEED" % ms, readonly=False) as t:
            ang = t.getcol("RECEPTOR_ANGLE")
            ang[:,0] = np.pi/2
            ang[:,1] = np.pi/2
            t.putcol("RECEPTOR_ANGLE", ang)
            fleetingpol.log.info("Receptor angle rotated by 90deg")

    recipe.add(__correct_feed_convention, "correct_feed_convention", {
              "ms": os.path.abspath(os.path.join(MSDIR, BP_CAL_MS)),
    },
input=INPUT, output=OUTPUT, label="correct_feed_convention")
```

**Comment by bennahugo** [comment]
As per discussion this requires both application when reading MODEL_DATA and inverse application when writing CORRECTED_DATA - similar to say enabling it in both gaincal and applycal

**Comment by o-smirnov** [comment]
I think we need separate independent options for both (rotate input, derotate output visibilities) to cover all the use cases.

**Comment by bennahugo** [comment]
done
