### ISSUE TITLE
CASA gain table export: PARAM err shape does not match PARAM shape

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#210]
Now that #203 is fixed, @bennahugo's MS throws up:

```
 - 18:23:35 - casa_db_adaptor    [io] [10.1/36.9 12.6/47.0 26.2Gb] Exporting to CASA gaintables
 - 18:23:35 - main               [io] [10.1/36.9 12.6/47.0 26.2Gb] I/O handler for load None save -1 failed with exception: PARAM err shape does not match PARAM shape, this is a bug
 - 18:23:35 - main               [io] [10.1/36.9 12.6/47.0 26.2Gb] Traceback (most recent call last):
  File "/home/oms/projects/CubiCal/cubical/workers.py", line 415, in _io_handler
    solver.gm_factory.close()
  File "/home/oms/projects/CubiCal/cubical/machines/abstract_machine.py", line 797, in close
    db.close()
  File "/home/oms/projects/CubiCal/cubical/database/casa_db_adaptor.py", line 458, in close
    self.__export()
  File "/home/oms/projects/CubiCal/cubical/database/casa_db_adaptor.py", line 443, in __export
    casa_caltable_factory.create_B_table(self, "G:gain")
  File "/home/oms/projects/CubiCal/cubical/database/casa_db_adaptor.py", line 216, in create_B_table
    assert db[gname].shape == db[gname + ".err"].shape, "PARAM err shape does not match PARAM shape, this is a bug"
AssertionError: PARAM err shape does not match PARAM shape, this is a bug
```

I suspect the fully-flagged intervals simply do not have an associated G.err entry in the table. Would it be easier to add a flagged G.err entry to the CubiCal databases, or can the CASA adapter code be fixed to cope with this situation? @bennahugo take a look and let's dicuss.

**Comment by bennahugo** [comment]
This is a simple check - we can fill the error column with infs when this happens and print a fat warning instead?

**Comment by bennahugo** [comment]
Hmm looking again at the code this is the shapes on the finalized table, so it is definitely a bug somewhere upstream from the database adaptor - either reconstruction of the database during finalize or the solver is dumping bogus for fully flagged intervals. I'll change it to a warning but there is no way to associate error to solutions when this happens.

**Comment by o-smirnov** [comment]
OK I'll dig in.
