### ISSUE TITLE
Be robust against null MODEL_DATA entries

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#222]
Another offshoot of https://github.com/ratt-ru/CubiCal/issues/211#issuecomment-417924093.

This is not our bug, but we need to be robust against this sort of thing... what happened here was, the MS in question has some MODEL_DATA visibilities that are 0 in positions that **aren't** flagged, originally. For example, check row 65, channel 12. Channels 0-11 are flagged, but valid MODEL_DATA only starts with channel 13. So it looks good enough to pass any reasonable eyeballing, but that sneaky channel 12 ruins everything...

Now this bit of code (responsible for estimating the prior variance on the solutions) divides by model-squared, in the happy assumption that the model can't be zero: https://github.com/ratt-ru/CubiCal/blob/master/cubical/machines/interval_gain_machine.py#L374. This results in an infinity that then propagates to the rest of the solution interval (because two lines down it takes the mean over the interval -- carefully zeroing out flagged entires, which this infinity isn't, for the reason above), thus zapping everything.

Anyway, I suppose the sensible thing to do is to check for null MODEL_DATA upfront (as we already check for null data and null weights) and flag those visibilities (with a big fat warning on the console that this is happening). 

In the meantime, @IanHeywood can you please check how you generate the model? Whichever tool is producing the missing channel, the bug has to be reported there...

**Comment by IanHeywood** [comment]
I'm using wsclean, in this case it was run in predict mode from a pre-existing set of model images.

**Comment by o-smirnov** [comment]
OK I think I have this working on the ``issue-222`` branch.

```
 - 23:48:20 - data_handler       [35.7/41.6 36.4/48.9 65.8Gb]   2.15% visibilities flagged due to 0/inf/nan model
```

...and then it reports solutions that are sensible and not out-of-control flagged (although the PGE seems high, so the default max-post-error would have clipped it heavily...) I'll leave it to run overnight to see if it completes.

**Comment by IanHeywood** [comment]
That was pretty heroic levels of user support, thanks. I'll try this tonight.

**Comment by o-smirnov** [comment]
Well I'm off for my mini-break as of tomorrow, so I shan't be doing more support until Monday next week -- hence my motivation to get this done!

Let me know how it works out though, I'm curious.

**Comment by o-smirnov** [comment]
P.S. Posterior gain error seems too high for my liking, something to look into when I'm back on the job. Although it only reports the maximum -- so maybe there's one bad antenna is all. You can try with --g-max-post-error back at the default, and see how much gets flagged -- if it's too much, then set it high again to bypass that check.

**Comment by IanHeywood** [comment]
Thanks!

**Comment by o-smirnov** [comment]
> You can try with --g-max-post-error back at the default, and see how much gets flagged

The answer is, 100%. So forget that idea for now -- leave it set high.
