### ISSUE TITLE
Setup.py - HELP!

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/CubiCal#236]
This is very much related to #232. Turns out that I was deluding myself with respect to the PyPI version. I create an sdist using python setup.py sdist, and this definitely successfully puts all the relevant files (including the .c and .cpp) files into a tarball. The problem is that when I attempt to install from the sdist tarball using pip (the same applies to installing from PyPI), it does not build the extensions (there are no .so files and the modules cannot be imported). I am getting fairly desperate at this point and would appreciate some help or being pointed in the direction of someone who can.

**Comment by JSKenyon** [comment]
Ok, I have posted a question about this on [StackOverflow](https://stackoverflow.com/questions/53151432/how-to-make-pip-setup-py-build-extensions-build-ext-when-installing-from-an-sd). I am giving up for the moment to focus on writing up my thesis. For any user finding this post, please follow the instructions for building from source for now.

**Comment by gijzelaerr** [comment]
are they included in the MANIFEST.in file?

**Comment by JSKenyon** [comment]
No... didn't think they would need to be. Will try that.

**Comment by JSKenyon** [comment]
The .c and .cpp files are definitely copying into the sdist. The build step never seems to happen though.

**Comment by JSKenyon** [comment]
This nightmare is approximately over.
