### ISSUE TITLE
ValueError: numpy.ufunc size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/CubiCal#256]
Ever seen this before? I suspect the installation has gone wrong somehow, but just checking.

Thanks.

```
 - 21:22:25 - main               [0.1/0.1 1.5/1.5 0.5Gb] defining chunks (time 32, freq 1024, also when SCAN_NUMBER jumps > 1.0)
 - 21:22:25 - data_handler       [0.1/0.1 1.5/1.5 0.5Gb]   read indexing columns (903168 total rows)
 - 21:22:25 - data_handler       [0.1/0.1 1.5/1.5 0.5Gb]   built timeslot index (448 unique timestamps)
 - 21:22:25 - data_handler       [0.1/0.1 1.5/1.5 0.5Gb]   max chunk size is 32 timeslots and/or -- seconds
 - 21:22:25 - main               [0.1/0.1 1.5/1.5 0.5Gb] Exiting with exception: ValueError(numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject)
 Traceback (most recent call last):
  File "/mnt/home/ianh/Software/CubiCal/cubical/main.py", line 357, in main
    chunks_per_tile=chunks_per_tile, max_chunks_per_tile=GD["dist"]["max-chunks"])
  File "/mnt/home/ianh/Software/CubiCal/cubical/data_handler/ms_data_handler.py", line 983, in define_chunk
    rebinning = cubical.kernels.import_kernel("rebinning")
  File "/mnt/home/ianh/Software/CubiCal/cubical/kernels/__init__.py", line 86, in import_kernel
    mod = importlib.import_module("cubical.kernels." + name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "__init__.pxd", line 918, in init cubical.kernels.rebinning
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

**Comment by o-smirnov** [comment]
Rebuild ought to fix that...

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by IanHeywood** [comment]
Indeed!

Cheers.

**Comment by IanHeywood** [comment]
Getting this when I run CubiCal on IDIA nodes no matter what I've tried so far. 

Tried a few fresh builds of `master` branch as well as `pol-cal-robust-merge`, and also a fresh virtualenv.

**Comment by bennahugo** [comment]
Its probably a build issue ian. Are you building from source? Otherwise
build a docker image (dockerfile in the repo) and import it with
singularity to make sure you're in a clean environment

**Comment by IanHeywood** [comment]
Yes, it's a build-from-source within a virtualenv.

I'm just a bit confused as I must have run it this way on IDIA machines a hundred times. Perhaps the node I'm building things on has changed configuration.

I will try what you suggest, thanks.

**Comment by IanHeywood** [comment]
> It could be that the system python is run regardless of whether you're in a venv or not. Try which python. And if that fails try putting the absolute path to your venv/bin/python2.7 /abspathtogocubical parset.cfg 

This fix seems to have worked, thanks.
