### ISSUE TITLE
do not clobber output files and logs when --out-name is the same

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#261]
Maybe it's my just sloppy habits, but I often re-run cubical with the same ``--out-name`` when experimenting... and then often find myself wishing I hadn't clobbered e.g. that previous logfile. It would be nice to have a default behaviour of **not** overwriting outputs if they already exist.

At the same time, I'd like a neat way of just dumping the outputs into a subdirectory. This is already supported, but needs to be a little smarter.

So, I propose:

* If set to ``--out-overwrite 1`` (default is 0!), revert to the current behavior of blindly overwriting outputs. Otherwise:

* If using ``--out-name name``, and ``name.log`` exists (i.e. there was a previous run), try ``name.0.log``, ``name.1.log``, etc., until we find one that doesn't exist, then use that basename for all output products (i.e. the output basename may turn out to be different from the one you specified, but them's the breaks).

* If using ``--out-name dir/name``, and ``dir/name.log`` exists, try ``dir.0``, ``dir.1``, etc., until we find ``dir.N`` that doesn't exist, then rename the current ``dir`` to ``dir.N``, and use ``dir/name`` for outputs. (The output dir will always be the one you specified -- it's the older output dir that gets moved out of the line of fire.)
 
* Implicitly treat ``--out-name dir/`` as ``--out-name dir/cubical`` for purposes of the above

* support substitutions of all settings-based patterns in the output name, as we do for ``--g-save-to`` (e.g. ``{data[ms]}``), as well as the patterns ``{host}``, ``{user}``, ``{date}``, ``{time}``.

@IanHeywood @bennahugo whhat do you think?

**Comment by bennahugo** [comment]
Sounds good. It will also be good to dump the gaintables to these directories for subsequent inspection

**Comment by o-smirnov** [comment]
Interesting that you should mention this... ``--JONES-save-to`` has a pattern that's based off the MS by default... but we can have a default based on the output name instead?

**Comment by bennahugo** [comment]
yea

**Comment by IanHeywood** [comment]
I think this all sounds great. I've always run CubiCal via a small Python script with:

```
import datetime
now = str(datetime.datetime.now()).replace(' ','-').replace(':','-').split('.')[0]
```

being passed to `--out-name`.

**Comment by o-smirnov** [comment]
@IanHeywood I remembered that habit of yours, that's why I thought of making it a standard feature. So you'd just have ``--out-name foo-{DATE}-{TIME}``.

BTW a neater way trick to making that same string is with ``datetime.datetime.now().strftime("%Y-%m-%d-%H-%M-%S")``

**Comment by o-smirnov** [comment]
OK I did this in my branch. Going to merge to master soon. Things like this work:

``--out-name myname-{DATE}-{TIME}-{USER}-{ENV[VAR]}/basename --g-save-to G-{out[name]}``

...where ``{section[variable]}`` references the current parset, and ``{ENV[VAR]}`` can even get at your shell environment variables.
