### ISSUE TITLE
Trying to compute stats for  un corrected residuals (out-mode = "as")

### ISSUE THREAD

**Issue by ulricharmel** [ratt-ru/CubiCal#265]
- 18:51:35 - main               [0.6/4.0 4.0/8.9 4.0Gb] computing summary statistics
 - 18:51:35 - main               [0.6/4.0 4.0/8.9 4.0Gb] Exiting with exception: AttributeError('NoneType' object has no attribute 'chanant')
 Traceback (most recent call last):
  File "/net/elwood/home/ulrich/cubenv/CubiCal/cubical/main.py", line 376, in main
    st = SolverStats(stats_dict)
  File "/net/elwood/home/ulrich/cubenv/CubiCal/cubical/statistics.py", line 38, in __init__
    self._concatenate(obj)
  File "/net/elwood/home/ulrich/cubenv/CubiCal/cubical/statistics.py", line 212, in _concatenate
    self.chanant = np.concatenate([stats[times[0], chan].chanant for chan in chans], axis=0)
AttributeError: 'NoneType' object has no attribute 'chanant'

I get the following error message when I try to apply gains only and compute un corrected residuals. Looking at this line https://github.com/ratt-ru/CubiCal/blob/master/cubical/main.py#L219 should'nt solver.subtract_only be part of the list?

**Comment by o-smirnov** [comment]
> should'nt solver.subtract_only be part of the list?

You're right. I'll fix it in my upcoming Big Merge.
