### ISSUE TITLE
Add KillMS style degridder to Cubical

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#268]
So I'm having very little luck with dE calibration and I'm suspecting bad modelling is top of the list why it is not working. I have 3 fields with dE sources, non of which improves even after painstakingly playing with solution intervals.

I can only conclude that the traditional DFT approach using pyBDSF fitted component models (on intrinsic scales) do not work for wideband instruments. I think it is worthwhile doing a more detailed comparison between KillMS and Cubical with models based solely on clean components.

For now the heavy handed kludge is to add a MODEL_DATA column for every direction that needs to be calibrated. This is not tractable for large 64 antenna datasets and it would be better to eventually replace the montblanc style DFT with a degridder that works based off a regions file and model images from either WSClean or DDFacet.

**Comment by KshitijT** [comment]
So spectral index estimation issues, no? The other way might be to use @landmanbester 's code from Codex Africanus to add spectral indices to the models; still need to get it working. :(

**Comment by bennahugo** [comment]
Yes it always heavily oversubtracts for me, which indicates the non-physical looking SPIs that pyBDSF spits out is indeed very non-physical. From what I can tell the calibration solutions indeed minimizes the chi^2 between the data and model, but this just absorbs modelling issues and most of the time it actually worsens the 2GC calibration on MK data.

**Comment by bennahugo** [comment]
You're quite right that we can try roll our own spi fitter, but I suspect clean components may still win out, because it models whatever the beam fails to model.

**Comment by KshitijT** [comment]
Yeah, the proof of pudding and stuff...

**Comment by bennahugo** [comment]
@IanHeywood not sure if you have any points of wisdom from your KillMS adventures?

**Comment by cyriltasse** [comment]
My experience is that it is this precise feature that makes `kMS` so good. LOFAR EoR have like 20.000 sources in their model, we can have millions of clean componants (it doesn't matter how many). They use GPUs, we use CPUs, and yet we're much much faster at doind DD selfcal (and actually they don't DD-selfcal, they just DDCal, DI-image)... I advice you go for it (using DDF for the DD-predict - making it easier for the interplay of DD-imaging DD-cal), I just regret (again) we don't have a single software for doing this...

The gridmachines are initialised [here](https://github.com/cyriltasse/killMS/blob/FixQ_PowerSmooth_DualPol_FlagAnts/Predict/ClassImageSM2.py), and the model visibilities in a given direction are computed i request here https://github.com/cyriltasse/killMS/blob/02a914f0f196b5b944c1ea787941b3b8a749e076/Predict/PredictGaussPoints_NumExpr5.py#L568
