### ISSUE TITLE
do we really need a hard montblanc/tensorflow dependency?

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#273]
The code has an exception handler around the ``import montblanc`` statements, and runs fine without Montblanc, unless an LSM is selected. But the new ``setup.py`` now crashes out if montblanc is not installed (complains about tensorflow). Is it wise to have this hard coupling?

**Comment by o-smirnov** [comment]
> Are you using python setup.py calls. If so don't. Use pip calls. 

But of course **facepalm**

This is exactly why I told @gijzelaerr that setup.py develop should throw an error if invoked explicitly. It's too much burned into muscle memory. I mean I had that argument two weeks ago, and I've already forgotten!

**Comment by gijzelaerr** [comment]
you can't, pip calls setup.py.
