### ISSUE TITLE
16.04 py2: Exiting with exception: RuntimeError(PycValueHolder: unknown python data type)

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#274]
New master crashes on 16.04/py2:
```
- 08:47:05 - data_handler       [2.6/14.9 8.1/20.5 7.8Gb]   inserting new column SC_PHASE_DATA
 - 08:47:05 - main               [2.6/14.9 8.1/20.5 7.8Gb] Exiting with exception: RuntimeError(PycValueHolder: unknown python data type)
 Traceback (most recent call last):
  File "/home/oms/projects/CubiCal/cubical/main.py", line 480, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/home/oms/projects/CubiCal/cubical/workers.py", line 212, in run_process_loop
    return _run_single_process_loop(ms, load_model, single_chunk, solver_type, solver_opts, debug_opts)
  File "/home/oms/projects/CubiCal/cubical/workers.py", line 351, in _run_single_process_loop
    tile.save(final=tile is tile_list[-1])
  File "/home/oms/projects/CubiCal/cubical/data_handler/ms_tile.py", line 1149, in save
    added = self.dh._add_column(self.dh.output_column)
  File "/home/oms/projects/CubiCal/cubical/data_handler/ms_data_handler.py", line 1374, in _add_column
    self.ms.addcols(desc, dminfo)
  File "/home/oms/.venv/cc/lib/python2.7/site-packages/python_casacore-3.0.0-py2.7-linux-x86_64.egg/casacore/tables/table.py", line 1228, in addcols
    self._addcols(tdesc, dminfo, addtoparent)
RuntimeError: PycValueHolder: unknown python data type
```
I'm afraid we have to support that combo for a bit yet, so let's figure out what this is. I suspect the python-casacore version installed by pip needs to be backed off to match the 16.04 casacore?

**Comment by bennahugo** [comment]
I'm seeing similar issues. This appears to be a casacore deficiency

casacore/python-casacore/issues/174

**Comment by bennahugo** [comment]
We will need a backport of casacore and python-casacore for 16.04 until end of support of the LTS

**Comment by bennahugo** [comment]
What happens if you build the latest casacore master from source @o-smirnov.

**Comment by bennahugo** [comment]
I propose
```
https://github.com/ratt-ru/CubiCal/blob/master/setup.py#L180 needs to be changed to <=2.1.2
```

**Comment by bennahugo** [comment]
This is a temporary kludge. Unfortunately we will need a KERN 3.1 release with backports for the latest casacore for Ubuntu 16.04 LTS.

**Comment by bennahugo** [comment]
> I propose
> 
> https://github.com/ratt-ru/CubiCal/blob/master/setup.py#L180 needs to be changed to <=2.1.2

That's a negative 'python-casacore<=2.2.1; python_version <= "2.7"' builds on Ubuntu 16.04 but not on Ubuntu 18.04. I think we're going to need a KERN 3.1 release to support Ubuntu 16.04

**Comment by o-smirnov** [comment]
Can't ``setup.py`` just check the casacore version and ask for an appropriate python-casacore version? Sound easier than backporting all of KERN.

**Comment by bennahugo** [comment]
Not quite. Wheels should be independent of base system (apart from being python 2.7 or python 3.0). The dependencies are not determined at install time, but at build time.

Can you try python-casacore 3.0.0? It looks like the lowest version I can have on both systems. If that version does not work please report the bug on python-casacore

**Comment by o-smirnov** [comment]
Well, what version did setup.py install pre-merge? It does smell like a python-casacore bug (still digging...), but if it is, shouldn't we be able to just go back to an older version? I don't know what a wheel is really, but I know this beast used to work.

Filed bug as https://github.com/casacore/python-casacore/issues/176

**Comment by JSKenyon** [comment]
Be wary - this might not be a python-casacore bug. I fixed on of these pre merge. There is likely a Unicode string in that call. If my hunch is correct, simply wrapping the offending argument in str() should fix it.

**Comment by o-smirnov** [comment]
Ah thanks @JSKenyon that is indeed the problem!

**Comment by o-smirnov** [comment]
Had to fix a similar problem here: https://github.com/ratt-ru/CubiCal/blob/master/cubical/data_handler/ms_data_handler.py#L864

How did this pass any tests?

**Comment by JSKenyon** [comment]
Indeed - we don't have 100% coverage and I imagine column insertion is on untouched branches. I would suggest tiny, patch PRs for these as they are found.

**Comment by o-smirnov** [comment]
The second instance was in ordinary column writing though...

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by JSKenyon** [comment]
I think that there is a [chance of an early return](https://github.com/ratt-ru/CubiCal/blob/de4d1162653509cb9e36e2b7451afc10d98b0fca/cubical/data_handler/ms_data_handler.py#L830) in that function. That first call already had the correct string wrapping and I am willing to bet that the tests always hit that return.
