### ISSUE TITLE
Pruning required

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/CubiCal#276]
Currently there are lots of vestigial branches on the repo that require pruning. I am responsible for some, @o-smirnov for others. This can be done using `git push --delete <remote_name> <branch_name>`.

**Comment by o-smirnov** [comment]
Or we can just do it via the github web interface, right?

**Comment by JSKenyon** [comment]
Almost certainly.

**Comment by JSKenyon** [comment]
I used the last of my cold medication induced productivity to apply the pruning shears liberally. If your branches have mysteriously disappeared, now you know why.
