### ISSUE TITLE
spurious error messages from logger

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#279]
```
Logged from file text.py, line 715
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 469, in format
    s = self._fmt % record.__dict__
KeyError: 'shortname'
```
I already see the problem/solution.

**Comment by o-smirnov** [comment]
Yeah so this was always broken (I shouldn't have been passing a custom format string to ``logging.basicConfig()``), but worked because I had the ``format`` keyword argument misspelt as ``fmt``. @gijzelaerr came along and fixed the spelling, thus exposing the original problem.

**Comment by gijzelaerr** [comment]
sorry!

**Comment by o-smirnov** [comment]
Let no good deed go unpunished!
