### ISSUE TITLE
Incorporating DDFacet degridder as a data source

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/CubiCal#284]
As discussed with @o-smirnov and @cyriltasse, it might be worth incorporating the relevant components from DDFacet. We can use this issue for discussion. That being said, I share @bennahugo's reservations regarding the extent to which CubiCal will become entangled with DDFacet. Thus, my first goal is to understand precisely what will be necessary to make it work and whether it will be maintainable.

**Comment by JSKenyon** [comment]
Due to an posting error on my part, prodding @o-smirnov, @bennahugo and @cyriltasse to make sure this gets seen.

**Comment by cyriltasse** [comment]
So the SkyModel class that's containing the predict machinary based on DDF is:

https://github.com/cyriltasse/killMS/blob/master/killMS/Predict/ClassImageSM2.py

And the place the degridder is called is called for predict in a given direction:

https://github.com/cyriltasse/killMS/blob/bc4dfcc05e5d202c8b240c9c6d18f9af227ef6b4/killMS/Predict/PredictGaussPoints_NumExpr5.py#L571
