### ISSUE TITLE
Discard completely flagged directions

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#294]
@o-smirnov @JSKenyon this issue deserves a separate issue from the degridding implementation.

I'm sure this issue has already been debated somewhere, but I don't know where to look.
There are cases where there is 0 or very little flux within a region and the solver should in those cases discard directions automatically (or probably just apply unity gains to the direction and subtract).

I'm wondering what the best way is to implement this within the framework. Maybe we can sit down and look at it in more detail tomorrow?

**Comment by o-smirnov** [comment]
Machinery is 99% there. This line resets gains to unity (i.e. ignoring solver updates) for the set of "fixed directions": https://github.com/ratt-ru/CubiCal/blob/master/cubical/machines/interval_gain_machine.py#L607

Currently, ``self.fix_directions`` is set up from ``--JONES-fix-dirs``. 

You can add code [here, roughly](https://github.com/ratt-ru/CubiCal/blob/master/cubical/machines/interval_gain_machine.py#L378) to detect directions with low model-to-noise, and add them to ``self.fix_directions`` auto-magically.

**Comment by bennahugo** [comment]
Ok so I'm going to impose a NSR constraint on all solutions of a direction if one of the solution dips below this the constraint the direction gets fixed. The correct thing is probably to weigh it by
NSR / \sum_{sols}NSR but my foo isn't good enough for this :)

**Comment by bennahugo** [comment]
Upon further inspection this is already implemented. However it could do with discarding INF PGE solutions. Fix incoming
