### ISSUE TITLE
3C147 DE calibration no longer works and introduces substantial ghosts

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#300]
I've played around with solution intervals on this one and imaged it with DDFacet and WSClean to make sure it is not a imager problem as we had before. Here is the DATA - 3C147 2GC image:
![image](https://user-images.githubusercontent.com/7934586/61829405-29f17580-ae69-11e9-84a0-e1276d77000a.png)
Doing 3GC results in a worse residual with the added bonus of definitive ghosts:
![image](https://user-images.githubusercontent.com/7934586/61829448-4097cc80-ae69-11e9-845e-a99c8521142a.png)

The following relevant options are set:
```
 22 [out]
 23 _Help = Options for output products
 24 name = subtract_dEs_lsm
 25 overwrite = True
 26 mode = sr
 27 column = LSM_DE_SUBTRACTED_DATA
 28 derotate = None
 29 model-column = MODEL_DATA
 30 weight-column =
 31 reinit-column = False
 32 subtract-model = 0
 33 subtract-dirs = 1:
 34 plots = 0
 35 casa-gaintables = False
 36 
 37 [model]
 38 _Help = Calibration model options
 39 list = 3C147_all.lsm.txt.de_tagged.lsm.html+-3C147_all.lsm.txt.de_tagged.lsm.html@dE:3C147_all.lsm.txt.de_tagged.lsm.html@dE
 40 ddes = auto
 41 beam-pattern = None
 42 beam-l-axis = None
 43 beam-m-axis = None
 44 feed-rotate = auto
 45 pa-rotate = False
190 [g]
191 _Help = Options for G-Jones term
192 label = G
193 solvable = True
194 type = complex-2x2
195 load-from =
196 xfer-from =
197 save-to = {data[ms]}/{JONES}-field_{sel[field]}-ddid_{sel[ddid]}.parmdb
198 dd-term = 0
199 fix-dirs =
200 update-type = full
201 time-int = 10
202 freq-int = 0
203 max-prior-error = 0.1
204 max-post-error = 0.1
205 clip-low = 0.1
206 clip-high = 10.0
207 clip-after = 5
208 max-iter = 100
209 epsilon = 1e-06
210 delta-chi = 1e-06
211 conv-quorum = 0.99
212 ref-ant = None
213 prop-flags = default
214 estimate-pzd = False
215 diag-only = 0
216 offdiag-only = False
217 robust-cov = hybrid
218 robust-npol = 2
219 robust-int = 5
220 robust-save-weights = False
221 diag-diag = False
222 _Templated = True
223 
224 [de]
225 _Templated = 1
226 solvable = True
227 type = complex-2x2
228 load-from =
229 xfer-from =
230 save-to = {data[ms]}/{JONES}-field_{sel[field]}-ddid_{sel[ddid]}.parmdb
231 fix-dirs = 0
232 update-type = full
233 time-int = 20
234 freq-int = 16
235 max-prior-error = 0.1
236 max-post-error = 0.1
237 clip-low = 0.0
238 clip-high = 0.0
239 clip-after = 5
240 max-iter = 100
241 epsilon = 1e-06
242 delta-chi = 1e-06
243 conv-quorum = 0.99
244 ref-ant = None
245 prop-flags = default
246 estimate-pzd = False
247 diag-only = 0
248 offdiag-only = False
249 robust-cov = hybrid
250 robust-npol = 2
251 robust-int = 5
252 robust-save-weights = False
253 diag-diag = False
```
The degridder does no beter or worse with very similar ghosts
Is there something I'm missing?

Btw - this is with my branch. Master is even more broken - it doubly applies P Jones when montblanc is used.

**Comment by bennahugo** [comment]
However what is perhaps a clue is somehow we end up with NAN/INF PNRs because my warning is now triggered:
```
 - 23:33:04 - parallactic_machin [x03] [0.8/1.3 4.1/6.9 45.0Gb] Applying P Jones to corrected data (precomputed)
 - 23:33:04 - solver             [x02] [0.8/1.3 3.8/6.9 45.1Gb] D0T23F1 has 12544 (7.14%) new data flags: gain flags LOWSNR:2(7.14%) (7.14% total)
 - 23:33:04 - parallactic_machin [x02] [0.8/1.3 4.1/6.9 45.1Gb] Applying P Jones to corrected data (precomputed)
 - 23:33:04 - solver             [x04] [1.1/1.3 4.1/6.9 45.5Gb] D0T22F1 has 57344 (7.14%) new data flags: gain flags LOWSNR:8(7.14%) (7.14% total)
 - 23:33:04 - parallactic_machin [x04] [1.1/1.3 4.4/6.9 45.5Gb] Applying P Jones to corrected data (precomputed)
 - 23:33:04 - solver             [x01] [1.1/1.3 4.1/6.9 45.7Gb] D0T22F0 has 57344 (7.14%) new data flags: gain flags LOWSNR:8(7.14%) (7.14% total)
 - 23:33:04 - parallactic_machin [x01] [1.1/1.3 4.4/6.9 45.7Gb] Applying P Jones to corrected data (precomputed)
 - 23:33:05 - solver             [x03] [1.0/1.3 4.0/6.9 46.7Gb] WARNING: one or more directions have invalid or 0 models (or frequency subbands). These dir
ections will not be solved for and residuals corrections left at unity!
 - 23:33:05 - solver             [x02] [1.0/1.3 4.0/6.9 46.7Gb] WARNING: one or more directions have invalid or 0 models (or frequency subbands). These dir
ections will not be solved for and residuals corrections left at unity!
 - 23:33:06 - solver             [x03] [1.0/1.3 4.0/6.9 47.1Gb] WARNING: one or more directions have invalid or 0 models (or frequency subbands). These dir
ections will not be solved for and residuals corrections left at unity!
 - 23:33:06 - solver             [x02] [1.0/1.3 4.0/6.9 47.2Gb] WARNING: one or more directions have invalid or 0 models (or frequency subbands). These dir
ections will not be solved for and residuals corrections left at unity!
 - 23:33:06 - solver             [x04] [1.0/1.3 4.0/6.9 47.4Gb] WARNING: one or more directions have invalid or 0 models (or frequency subbands). These dir
ections will not be solved for and residuals corrections left at unity!
 - 23:33:06 - solver             [x01] [1.0/1.3 4.0/6.9 47.5Gb] WARNING: one or more directions have invalid or 0 models (or frequency subbands). These directions will not be solved for and residuals corrections left at unity!
 - 23:33:06 - solver             [x04] [1.0/1.3 4.0/6.9 47.9Gb] WARNING: one or more directions have invalid or 0 models (or frequency subbands). These directions will not be solved for and residuals corrections left at unity!
 - 23:33:06 - solver             [x01] [1.0/1.3 4.0/6.9 48.0Gb] WARNING: one or more directions have invalid or 0 models (or frequency subbands). These directions will not be solved for and residuals corrections left at unity!
 - 23:33:06 - data_handler       [io] [3.4/23.3 45.5/61.5 48.4Gb]   computing visibilities for 3C147_all.lsm.txt.de_tagged.lsm.html
 - 23:33:06 - data_handler       [io] [3.4/23.3 51.0/61.5 48.4Gb] montblanc dtype is complex128 ('double')

```

**Comment by o-smirnov** [comment]
Same result on the master branch? Strikes me as something similar to @IanHeywood's recent woes...

**Comment by bennahugo** [comment]
master does not work remember - you doubly apply P.

**Comment by bennahugo** [comment]
Something is wrong with the model because that warning should not be triggered with an lsm produced model. I will have a look again with fresh eyes in the morning. Perhaps you can look at the bit of code in the interval gain machine and tell me if I'm being and idiot

**Comment by JSKenyon** [comment]
I am making some progress on this. Currently, all directions other than the first end up having jhjinv equal to zero. This is because the low SNR flag bit is set everywhere. I am busy trying to figure out how/why this happens.

**Comment by JSKenyon** [comment]
@bennahugo Your edits to [this function](https://github.com/ratt-ru/CubiCal/blob/6138b77e9bc0e0e234b1160fbfa980a1e44ab8f4/cubical/machines/interval_gain_machine.py#L339) may be at fault. I will double check the behaviour of master.

**Comment by JSKenyon** [comment]
I can confirm that this bug is not in master. Currently rerunning my tests with the current master - will post my findings shortly.

**Comment by JSKenyon** [comment]
I am running into division by zero errors on master. I believe these may have always existed, but were quietly ignored by Cython. The Numba code has exposed this behaviour.

**Comment by bennahugo** [comment]
> @bennahugo Your edits to [this function](https://github.com/ratt-ru/CubiCal/blob/6138b77e9bc0e0e234b1160fbfa980a1e44ab8f4/cubical/machines/interval_gain_machine.py#L339) may be at fault. I will double check the behaviour of master.

@JSKenyon that function had a clear bug which resulted in 100% flags written to disk when one of the directions were empty. I believe the following defaults are really the cause of the 'bug'
```
[de]
_Help = Options for DE-Jones term
label = DE
solvable = True
type = complex-2x2
load-from = 
xfer-from = 
save-to = {data[ms]}/{JONES}-field_{sel[field]}-ddid_{sel[ddid]}.parmdb
dd-term = 1
fix-dirs = 0
update-type = full
time-int = 20
freq-int = 16
max-prior-error = 0.1
max-post-error = 0.1
```
Who set the SNR requirements to 10x -- not even CASA bandpass has this strict a requirement?!

On another note the logs are not verbose enough if this slips past both you and me. Shall we print scores of big fat red warnings in this case?

**Comment by JSKenyon** [comment]
I would like @o-smirnov to weigh in on this one. I have some fundamental gaps in my knowledge regarding those error estimates.

**Comment by JSKenyon** [comment]
> > @bennahugo Your edits to [this function](https://github.com/ratt-ru/CubiCal/blob/6138b77e9bc0e0e234b1160fbfa980a1e44ab8f4/cubical/machines/interval_gain_machine.py#L339) may be at fault. I will double check the behaviour of master.
> 
> @JSKenyon that function had a clear bug which resulted in 100% flags written to disk when one of the directions were empty. I believe the following defaults are really the cause of the 'bug'
> 
> ```
> [de]
> _Help = Options for DE-Jones term
> label = DE
> solvable = True
> type = complex-2x2
> load-from = 
> xfer-from = 
> save-to = {data[ms]}/{JONES}-field_{sel[field]}-ddid_{sel[ddid]}.parmdb
> dd-term = 1
> fix-dirs = 0
> update-type = full
> time-int = 20
> freq-int = 16
> max-prior-error = 0.1
> max-post-error = 0.1
> ```
> 
> Who set the SNR requirements to 10x -- not even CASA bandpass has this strict a requirement?!
> 
> On another note the logs are not verbose enough if this slips past both you and me. Shall we print scores of big fat red warnings in this case?

Just to be clear, this doesn't happen on master. So while I am perfectly willing to believe it was bugged, I am still concerned that the changes alter the working aspects of its behaviour. Although I may have misunderstood something.

**Comment by o-smirnov** [comment]
OK ok I see what's going on. It's not a bug it's a feature!

> Who set the SNR requirements to 10x -- not even CASA bandpass has this strict a requirement?!

I did. :) It's my high-DR bias. The 0.1 number originated in the context of G solutions. Argument being, if your DI selfcal is not good enough to get you to within 0.1 radian of phase, there's something wrong with your data or model, and red flags need to be raised. My contention is that for a typical MeerKAT L-band observation this is indeed the case.

Firstly, it's clearly a mistake propagating this same default onto DD solutions. DD models can have much lower SNR, and a higher solution error could still be perfectly adequate for peeling. So we need to set it to .33 or so for the dE case.

Secondly, why the master version works. That's because it's pretty chilled about flags on dE gains in the first place. See the ``--de-prop-flags`` setting (and documentation on it). Gainflags on dE's may be raised, but the update rule is still cheerfully computed and applied (see [restrict_solutions()](https://github.com/ratt-ru/CubiCal/blob/master/cubical/machines/interval_gain_machine.py#L587)? It does nothing with the flags). Essentially, dE gainflags are ignored by default. @bennahugo is right -- it would have been better to at least print a fat red warning!

On @bennahugo's branch, he's gotten a lot stricter about actually doing something with the flagged dE's -- hence exposing the original problem of the default error threshold being too strict.

All explained now?

**Comment by bennahugo** [comment]
I shall implement said fat red warning. We probably need stick shakers and alarm bells installed as well :)

**Comment by o-smirnov** [comment]
Yep, maybe something along the lines of "de: X gain flags raised". This should be in the convergence status string somehow (though we don't have provisions to make part of the string red... perhaps we should...)

**Comment by bennahugo** [comment]
I was thinking separate and significantly more informative warning, with an explicit prefix 
```MASTER WARNING: Low SNR flags raised for direction {1:d}! This likely indicates user error. NO CALIBRATION CORRECTIONS SHALL BE MADE. Check your solution intervals and settings for max-prior-error on your gain terms!
``` 
https://github.com/ratt-ru/CubiCal/blob/6138b77e9bc0e0e234b1160fbfa980a1e44ab8f4/cubical/machines/interval_gain_machine.py#L339

**Comment by JSKenyon** [comment]
Indeed. That being said, I am fairly certain that something is broken in the chain machine logic. I am busy figuring it out but it seems that the cached model array ends up containing very large values in certain circumstances.

**Comment by o-smirnov** [comment]
What's a **MASTER WARNING**? Is it more serious, and substantially redder, than a **WARNING**? :P 

Things to consider (I'm reading a book about nuclear reactor accidents right now, so feeling philosophical about UI issues):

* Too many warnings is as bad as no warnings at all (the cry wolf effect)

* If you just print it at the proposed location, you'll get a slew of repeated warnings, one per every solution chunk, drowning out the rest of the output. I find software like that very annoying. 

* Some DD models in some chunks **can** actually legitimately go to near-zero (think of a source near a beam null) and this is perfectly ok. If you hammer the user with warnings in this situation, you'll just habituate them to warnings in what is a perfectly normal operational scenario.

I would propose a more subtle report on the number of gainflags raised -- perhaps escalating to loud redness if this is over some (configurable?) fraction.

**Comment by JSKenyon** [comment]
Ok, I am still a bit confused. The LOWSNR flag is raised on the dE gains and those flags are passed into the compute_inverse function. So any dE flagged as LOWSNR does not get updated. That makes some sense, but on the 3C147 test, setting max-prior-error and max-posterior-error to one still results is 68% LOWSNR flags on the dE term. This is with (8,8) solution intervals, which I know from previous experiments works. Does that make any sense @o-smirnov?

**Comment by bennahugo** [comment]
Hmm, I'm watching aircraft crash investigations at the moment. I'm also feeling philosophical:

British Midland 92 could have been prevented if the engine vibration meter of the left hand engine wasn't **subtly** hidden away in the fancy new cockpit LCD displays (at the time).

```
The Kegworth Air Accident (1989)
....
The EIS which was fitted to the B737-400 used digital rather than analogue displays.
A subsequent survey showed that nearly two-thirds of BMA pilots believed that the
new EIS was not effective in drawing their attention to rapid changes in the engine
parameters,  and  nearly  three-quarters  preferred  the  old  EIS.  Thus,  the  system
designers of the EIS and the training could be deemed to have contributed to the
accident. It appears that the pilots of BMA (at least) were not involved in carrying
out any evaluation of the new EIS before they had to use it in flight.
```

**Comment by bennahugo** [comment]
But I agree too much warning is a bad thing. I will attempt to make it print once if total LOWSNR flags exceeds tolerance. User warnings should most likely be fatal unless the user explicitly pulls the "breaker" for the "alarmbell".

**Comment by JSKenyon** [comment]
So these LOWSNR flags are definitely part of the problem. With fewer LOWSNR flags (about 68% of the dE solutions were still flagged), dE calibration begins to work again.

![better](https://user-images.githubusercontent.com/6582745/61949217-5c56bc00-afaa-11e9-8305-3cba59247e6c.png)

**Comment by o-smirnov** [comment]
> but on the 3C147 test, setting max-prior-error and max-posterior-error to one still results in 68% LOWSNR flags on the dE term.

On master?

**Comment by JSKenyon** [comment]
@o-smirnov No, this is back on ddf_inc. Decided that trying to fix master was wasted effort given that @bennahugo has already fixed the flagging bug.

**Comment by o-smirnov** [comment]
> No, this is back on ddf_inc. Decided that trying to fix master was wasted effort

I would argue that master is not broken in the first place. Or is it? 

You say "setting max-prior-error and max-posterior-error to one still results in 68% LOWSNR flags on the dE term" -- this is clearly incorrect behaviour, so could you please check if this is also the case on master. If not, then it's @bennahugo's changes that have introduced the problem.

**Comment by bennahugo** [comment]
#301 breaks dE calibration on master

**Comment by bennahugo** [comment]
In order to test master you will need to cherry pick out my fixes for it

**Comment by o-smirnov** [comment]
OK so master might not converge to the right solution because of #301, fine -- I just want to know if it throws up those LOWSNR flags. Which it shouldn't.

**Comment by JSKenyon** [comment]
Master doesn't seem to be applying LOWSNR in the same way. That being said, I am struggling to get a run to complete due to a division by zero error. It looks like my instincts were correct - something is awry in flagging land. A brief summary of my current findings:

- Overly aggressive LOWSNR flagging on ddf_inc is causing dE calibration to fail.
- On both master and ddf_inc, we run into division by zero errors if the dE gains explode. These need to be caught and set to identity. We were likely missing this behaviour in Cython as it was configured to ignore divide by zero errors.
- In general, we need to be much smarter about handling/catching bad dE solutions.

**Comment by JSKenyon** [comment]
That being said, I think maybe my generic inverse kernel should be trapping the divide by zeros. I see now that the eps value is possibly going to drop below machine precision. Will update if changing this helps.

**Comment by JSKenyon** [comment]
See #303 for an intertwined bug which has been tripping me up all day.
