### ISSUE TITLE
User warnings

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#302]
Continuing from #300 

I propose 3 special 'user warning' log levels, with spacing instead of colours:
```
CAUTION: ... non fatal
WARNING: ... non fatal
STICK SHAKER (or equivalent): .... fatal
```
or Chernobyl-style for @o-smirnov 
```
 REACTOR UNDER POWER
 REACTOR OVER POWER
 REACTOR COOLANT LOSS
```
the last one of which ominously starts playing classical music over the wired radio in the kitchen...

**Comment by bennahugo** [comment]
(@JSKenyon https://www.youtube.com/watch?v=1CJoF4Z_-Ro?3m40 for context )

**Comment by JSKenyon** [comment]
I would like to err on the side summarized log messages from now on. Multi-processing already creates a log-storm and additional messages can only make it worse. I do agree that we need to inform the user of these things, but at the same time I think we need a way to compress these logging messages into something a little more digestible.

**Comment by o-smirnov** [comment]
I propose we follow the pattern of the "convergence status string" reporting mechanism that's already defined by the machines (note that the chain machine already collects statuses from individual terms), at least in spirit.

* add a method to the abstract machine called e.g. ``raise_warning(level, message, short_label)``, which adds a warning message to an internal list

* add a method called ``collect_warnings()``, which returns the list. Chain machine implements this in terms of collecting warnings from individual Jones terms.

* when printing the convergence status of a given chunk, collect the machine's warnings, and tack on a short (red) suffix onto the convergence string if any warnings are raised. E.g. "#W:X,Y,Z", where X,Y,Z is a list of the ``short_label``s as passed in above. (Having something like "#W" as a prefix is very handy, because you can then grep the log for warnings).

* return the list of warnings [here](https://github.com/ratt-ru/CubiCal/blob/master/cubical/solver.py#L856) and collect it [here](https://github.com/ratt-ru/CubiCal/blob/master/cubical/workers.py#L301). 

* if any warnings are raised, print a red summary at the end of the tile (or perhaps just at the end of the run?)

**Comment by o-smirnov** [comment]
The "final chunk status" message is formed up [here](https://github.com/ratt-ru/CubiCal/blob/master/cubical/solver.py#L346), so that's where we would tack on a red warnings suffix.

**Comment by bennahugo** [comment]
ok I've done an initial pass. the solver log messages need to be appended onto the stack and further passed down @o-smirnov . I'm also now printing the actual level which helps a lot - I don't quite agree with the current strategy of solely relying on colours
```
WARNING - 00:37:38 - ms_tile            [io] [1.8/23.3 39.1/61.8 3.2Gb]   6.27% input visibilities flagged as invalid (0/inf/nan)
WARNING - 00:37:38 - ms_tile            [io] [1.8/23.3 39.1/61.8 3.2Gb]   6.26% input visibilities flagged due to null weights
INFO - 00:37:38 - ms_tile            [io] [1.8/23.3 39.1/61.8 3.2Gb]   12.54% input visibilities flagged and/or deselected
CRITICAL - 00:37:41 - solver             [x08] [1.1/1.3 4.0/6.9 3.7Gb] 'DE' D0T3F1 Low SNR in directions 0, 7, 8, 9. Increase solution intervals or raise max-prior-error!
CRITICAL - 00:37:42 - solver             [x12] [1.6/2.0 4.7/7.4 3.7Gb] 'DE' D0T5F1 Low SNR in directions 0, 7, 8, 9. Increase solution intervals or raise max-prior-error!
CRITICAL - 00:37:42 - solver             [x06] [1.6/2.0 4.7/7.4 3.7Gb] 'DE' D0T2F1 Low SNR in directions 0, 7, 8, 9. Increase solution intervals or raise max-prior-error!
CRITICAL - 00:37:42 - solver             [x10] [1.6/2.0 4.7/7.4 3.7Gb] 'DE' D0T4F1 Low SNR in directions 0, 7, 8, 9. Increase solution intervals or raise max-prior-error!
CRITICAL - 00:37:42 - solver             [x14] [1.6/2.0 4.7/7.4 3.7Gb] 'DE' D0T6F1 Low SNR in directions 0, 7, 8, 9. Increase solution intervals or raise max-prior-error!
CRITICAL - 00:37:42 - solver             [x04] [1.6/2.0 4.7/7.4 3.7Gb] 'DE' D0T1F1 Low SNR in directions 0, 7, 8, 9. Increase solution intervals or raise max-prior-error!
CRITICAL - 00:37:42 - solver             [x02] [1.6/2.0 4.6/7.3 3.7Gb] 'DE' D0T0F1 Low SNR in directions 0, 7, 8, 9. Increase solution intervals or raise max-prior-error!
INFO - 00:37:43 - ms_tile            [io] [2.3/23.3 42.2/61.8 3.8Gb]   computing visibilities for 3C147_all.lsm.txt.de_tagged.lsm.html
INFO - 00:37:49 - solver             [x15] [0.8/0.9 3.8/6.9 3.8Gb] D0T7F0 has 24160 (9.63%) new data flags: gain flags LOWSNR:2(7.14%) (7.14% total)
CRITICAL - 00:37:50 - solver             [x15] [0.8/1.0 3.8/6.9 3.8Gb] 'DE' D0T7F1 Low SNR in directions 0, 6, 7, 8, 9. Increase solution intervals or raise max-prior-error!
INFO - 00:37:51 - solver             [x15] [0.8/1.0 3.8/6.9 3.8Gb] D0T7F1 has 17920 (7.14%) new data flags: gain flags LOWSNR:2(7.14%) (7.14% total)
INFO - 00:37:51 - solver             [x08] [1.2/1.4 4.1/6.9 3.8Gb] D0T3F1 has 34048 (7.14%) new data flags: gain flags LOWSNR:4(7.14%) (7.14% total)
INFO - 00:37:51 - solver             [x07] [1.2/1.4 4.1/6.9 3.8Gb] D0T3F0 has 45904 (9.63%) new data flags: gain flags LOWSNR:4(7.14%) (7.14% total)
```
Higher verbosity makes these messages more verbose with stats etc... see my branch

**Comment by bennahugo** [comment]
I also only print chunks with chi^2 diverging in level 0

**Comment by o-smirnov** [comment]
> I'm also now printing the actual level which helps a lot - I don't quite agree with the current strategy of solely relying on colours

Yeah good idea. Suggest padding the severity field though so that the rest of the message is aligned.

**Comment by bennahugo** [comment]
ok alignment and colouring added. CRITICAL and ERROR also blinks on normal ttys - this is as close to a stick shaker I can get

**Comment by o-smirnov** [comment]
Really not sure about the blinking, @bennahugo... why don't we activate the office fire alarm while we're at it?

**Comment by bennahugo** [comment]
Fixed to some degree. I think this going to be an ongoing process, because some messages are still being printed as info and should really be at the WARNING or CRITICAL level

**Comment by o-smirnov** [comment]
> some messages are still being printed as info and should really be at the WARNING or CRITICAL level

That's what we call CRITICAL INFORMATION!
