### ISSUE TITLE
first term in sol-term-iters is not replicated and prevents dE calibration

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#305]
Not sure where this is coming from but it is None for dE terms

**Comment by bennahugo** [comment]
On further inspection
```
130     def implement_update(self, jhr, jhjinv):
131 
132         # jhjinv is 2x2 block-diagonal, with Hermitian blocks. TODO: what's the variance on the off-diagonals?
133         # variance of gain is diagonal of jhjinv
134         if self.dd_term:
135             import ipdb; ipdb.set_trace()
```
is never triggered.... @o-smirnov any ideas?

**Comment by bennahugo** [comment]
This is not triggering on the weighted 2x2 machine either.

**Comment by bennahugo** [comment]
first term in sol-term-iters is not replicated and prevents dE calibration. This is the source of our dE woes

**Comment by bennahugo** [comment]
@o-smirnov @IanHeywood take note: it looks like you need a number of iters per gain term in order for the chain to be even solved. There are no warnings if you don't have it and it only updates the first term!

**Comment by bennahugo** [comment]
As far as I can tell there is no logic to handle it here before the machinery reads the GD

**Comment by o-smirnov** [comment]
But that was by design. It goes over as many Jones terms as there are items in term-iter. If that's less than the length of the chain, so be it. Sorry if this caused confusion!

**Comment by o-smirnov** [comment]
A warning is warranted, or perhaps it needs to be auto-replicated. But it's fairly obvious when a term is not solved for, no?

**Comment by bennahugo** [comment]
no it is not obvious at all (at least not in an easily identifiable way quoting @JSKenyon) . I only spotted it when I was debugging. I think the default should replicate up to at least solving once per term.

**Comment by bennahugo** [comment]
(so if you don't want to solve a term remove it from your sol terms instead)

**Comment by bennahugo** [comment]
I've implemented the fix with a warning to the user

**Comment by o-smirnov** [comment]
> no it is not obvious at all (at least not in an easily identifiable way quoting @JSKenyon)

The convergence status string should contain an entry from each iterated term. Granted, this is not obvious to a newbie user.

**Comment by bennahugo** [comment]
Ok well I still don't quite know how to properly read these convergence messages then. I've now also revised them to only print on divergence (if solving works the user need not be told it works in my opinion).

The following warning will now be printed:
```
WARNING    - 12:00:51 - main               [0.2/0.2 2.7/2.7 13.1Gb] Multiple gain terms specified, but a recipe of solver sol-term-iters not given. This may indicate user error. We will assume doing the same number of iterations per term and stopping on the last term on the chain.
```

**Comment by o-smirnov** [comment]
> Ok well I still don't quite know how to properly read these convergence messages then. I've now also revised them to only print on divergence (if solving works the user need not be told it works in my opinion).

I disagree. Once you know what to look for, these statuses are actually a useful QA and postmortem analysis tool, especially when something looks slightly funny afterwards. I would much rather have them on by default. Otherwise I can promise you that pretty much every single CubiCal question is going to be met with an "I dunno, please rerun your job with a higher verbosity level", which is just a waste of time all around.

**Comment by bennahugo** [comment]
Ok I will change them back. However they should be more human readable with helpful messages in case of divergence

**Comment by IanHeywood** [comment]
> Once you know what to look for, these statuses are actually a useful QA and postmortem analysis tool 

As a button-pushing astronomer with aspirations of intermediate level CubiCal user status, I agree completely.

**Comment by bennahugo** [comment]
Fixed
