### ISSUE TITLE
IFR gains are wrong

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#313]
I've been scratching my head on this one and it appears the IFR gains are wrong (or has some sort of normalization applied that I don't understand. If we look at m060 after CASA solved for the chain there are definitely closure problems (coloured here by baseline, stable in time):
![image](https://user-images.githubusercontent.com/7934586/63920635-97cd2600-ca41-11e9-98c7-ff41e81ec64d.png)

However, with cubical the IFR gains predict a ball which is clearly not true if you look at the corrected data:
![image](https://user-images.githubusercontent.com/7934586/63920714-bb906c00-ca41-11e9-9db2-09f84838f42e.png)

**Comment by bennahugo** [comment]
Nevermind... This is what I get from CASA
![image](https://user-images.githubusercontent.com/7934586/63927234-9275d880-ca4d-11e9-870a-84da75c50c64.png)

**Comment by o-smirnov** [comment]
Yeah a head scratcher. I agree with your logic -- if it's a stable phase offset in time, an IFR gain should just rotate it back to zero -- but the consistent results from cubical and CASA suggest we're missing something.
