### ISSUE TITLE
Applying gains in Cubical results in Error

### ISSUE THREAD

**Issue by PeterKamphuis** [ratt-ru/CubiCal#315]
When running Cubical through [Stimela](https://github.com/SpheMakh/Stimela) I get the following error several times  when I try to apply previously derived gains.

meerkathi - 2019-09-04 16:54:27,520 INFO - ERROR - 14:54:24 - solver [x03] [0.8/0.9 1.8/2.2 0.9Gb] Solver for tile 0 chunk D0T2F0 failed with exception: Failed in nop
ython mode pipeline (step: nopython frontend)
meerkathi - 2019-09-04 16:54:27,520 INFO - Unknown attribute 'shape' of type none
meerkathi - 2019-09-04 16:54:27,520 INFO -
meerkathi - 2019-09-04 16:54:27,520 INFO - File "../../usr/local/lib/python2.7/dist-packages/cubical/kernels/diag_phase_only.py", line 69:
meerkathi - 2019-09-04 16:54:27,520 INFO - def compute_jhj(m, jhj, t_int=1, f_int=1):
meerkathi - 2019-09-04 16:54:27,520 INFO - 
meerkathi - 2019-09-04 16:54:27,521 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO - n_dir = m.shape[0]
meerkathi - 2019-09-04 16:54:27,521 INFO - ^
meerkathi - 2019-09-04 16:54:27,521 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO - [1] During: typing of get attribute at /usr/local/lib/python2.7/dist-packages/cubical/kernels/diag_phase_only.py (69)
meerkathi - 2019-09-04 16:54:27,521 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO - File "../../usr/local/lib/python2.7/dist-packages/cubical/kernels/diag_phase_only.py", line 69:
meerkathi - 2019-09-04 16:54:27,521 INFO - def compute_jhj(m, jhj, t_int=1, f_int=1):
meerkathi - 2019-09-04 16:54:27,521 INFO - 
meerkathi - 2019-09-04 16:54:27,521 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO - n_dir = m.shape[0]
meerkathi - 2019-09-04 16:54:27,521 INFO - ^
meerkathi - 2019-09-04 16:54:27,521 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO - This is not usually a problem with Numba itself but instead often caused by
meerkathi - 2019-09-04 16:54:27,521 INFO - the use of unsupported features or an issue in resolving types.
meerkathi - 2019-09-04 16:54:27,521 INFO -
meerkathi - 2019-09-04 16:54:27,521 INFO - To see Python/NumPy features supported by the latest release of Numba visit:
meerkathi - 2019-09-04 16:54:27,521 INFO - http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
meerkathi - 2019-09-04 16:54:27,522 INFO - and
meerkathi - 2019-09-04 16:54:27,522 INFO - http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
meerkathi - 2019-09-04 16:54:27,522 INFO -
meerkathi - 2019-09-04 16:54:27,522 INFO - For more information about typing errors and how to debug them visit:
meerkathi - 2019-09-04 16:54:27,522 INFO - http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
meerkathi - 2019-09-04 16:54:27,522 INFO -
meerkathi - 2019-09-04 16:54:27,522 INFO - If you think your code should work with Numba, please report the error message
meerkathi - 2019-09-04 16:54:27,522 INFO - and traceback, along with a minimal reproducer at:
meerkathi - 2019-09-04 16:54:27,522 INFO - https://github.com/numba/numba/issues/new

Cubical seems to continue while throwing that error several time more and then stimela exits with a critical error:

utils.StimelaCabRuntimeError: gocubical: returns errr code 1

I used the following parset:

[data]
_Help = Visibility data options
ms = /scratch/msdir/Quick-GRB111005A_corr.ms
column = DATA
time-chunk = 128
freq-chunk = 0
rebin-time = 1
rebin-freq = 1
chunk-by = SCAN_NUMBER
chunk-by-jump = 1
single-chunk =
single-tile = -1

[sel]
_Help = Data selection options
field = 0
ddid = None
taql =
chan =
diag = True

[out]
_Help = Options for output products
dir = cubical
name = /scratch/output/continuum/selfcal_products/Quick-Quick-GRB111005A_corr.ms_2_restored_cubical
overwrite = False
backup = 1
mode = ac
apply-solver-flags = True
column = CORRECTED_DATA
derotate = None
model-column =
weight-column =
reinit-column = False
subtract-model = 0
subtract-dirs = :
plots = 1
casa-gaintables = False

[model]
_Help = Calibration model options
list =
ddes = never
beam-pattern = None
beam-l-axis = None
beam-m-axis = None
feed-rotate = auto
pa-rotate = True

[montblanc]
_Help = Montblanc simulation options
device-type = CPU
dtype = float
mem-budget = 1024
verbosity = WARNING
threads = 0
pa-rotate = None

[weight]
_Help = Weighting options
column = WEIGHT
fill-offdiag = False
legacy-v1-2 = False

[flags]
_Help = General flagging options
apply = -cubical
auto-init = legacy
save = cubical
save-legacy = auto
reinit-bitflags = False
warn-thr = 0.3
see-no-evil = 0

[degridding]
_Help = Options for the degridder. Only in use when predicting from DicoModels using DDFacet
OverS = 11
Support = 7
Nw = 100
wmax = 0.0
Padding = 1.7
NDegridBand = 16
MaxFacetSize = 0.25
MinNFacetPerAxis = 1
NProcess = 8

[postmortem]
_Help = Options for "postmortem" flagging based on solution statistics
enable = False
tf-chisq-median = 1.2
tf-np-median = 0.5
time-density = 0.5
chan-density = 0.5
ddid-density = 0.5

[madmax]
_Help = Options for the "Mad Max" flagger
enable = 1
residuals = 0
estimate = corr
diag = True
offdiag = False
threshold = [0, 5]
global-threshold = [0, 12]
plot = 0
plot-frac-above = 0.01
plot-bl =
flag-ant = 0
flag-ant-thr = 5

[sol]
_Help = Solution options which apply at the solver level
jones = G
precision = 32
delta-g = 1e-06
delta-chi = 1e-06
chi-int = 5
last-rites = True
stall-quorum = 0.99
term-iters = 0
min-bl = 0.0
max-bl = 0
subset =

[bbc]
_Help = Options for baseline-based corrections (a.k.a. BBCs, a.k.a. interferometer gains).
load-from =
compute-2x2 = False
apply-2x2 = False
save-to = file
per-chan = True
plot = True

[dist]
_Help = Parallelization and distribution options
ncpu = 6
nworker = 0
nthread = 0
max-chunks = 0
min-chunks = 0
pin = 0
pin-io = False
pin-main = io

[log]
_Help = Options related to logging
memory = True
stats = chi2:.3f
stats-warn = chi2:10
boring = False
append = False
verbose = 0
file-verbose = None

[debug]
_Help = Debugging options for the discerning masochist
pdb = False
panic-amplitude = 0.0
stop-before-solver = False
escalate-warnings = False

[misc]
_Help = Miscellaneous options
random-seed = None
parset-version = 0.1

[JONES-TEMPLATE]
_Help = Options for {LABEL}-Jones term
_NameTemplate = {LABEL}
_ExpandedFrom = --sol-jones
OtherTemplates = Help:label
label = {LABEL}
solvable = 1
type = complex-2x2
load-from =
xfer-from =
save-to = {out[name]}-{JONES}-field{sel[field]}-ddid{sel[ddid]}.parmdb
dd-term = False
fix-dirs =
update-type = full
time-int = 1
freq-int = 1
max-prior-error = 0.1
max-post-error = 0.1
low-snr-warn = 75
high-gain-var-warn = 30
clip-low = 0.1
clip-high = 10.0
clip-after = 5
max-iter = 20
epsilon = 1e-06
delta-chi = 1e-06
conv-quorum = 0.99
ref-ant = None
prop-flags = default
estimate-pzd = False
diag-only = 0
offdiag-only = False
robust-cov = compute
robust-scale = 1
robust-npol = 2
robust-int = 1
robust-save-weights = 0

[g]
Help = Options for G-Jones term
label = G
solvable = 0
type = phase-diag
load-from =
xfer-from = /scratch/output/continuum/selfcal_products/g-gains-2-Quick-GRB111005A_corr.parmdb
save-to = {out[name]}-{JONES}-field{sel[field]}-ddid_{sel[ddid]}.parmdb
dd-term = 0
fix-dirs =
update-type = phase-diag
time-int = 5
freq-int = 0
max-prior-error = 0.1
max-post-error = 0.1
low-snr-warn = 75
high-gain-var-warn = 30
clip-low = 0.1
clip-high = 10
clip-after = 5
max-iter = 20
epsilon = 1e-06
delta-chi = 1e-06
conv-quorum = 0.99
ref-ant = None
prop-flags = default
estimate-pzd = False
diag-only = 0
offdiag-only = False
robust-cov = compute
robust-scale = 1
robust-npol = 2
robust-int = 1
robust-save-weights = 0
_Templated = True

[de]
_Templated = 1
dd-term = 1
clip-low = 0.0
clip-high = 0
delta-chi = 1e-05
max-prior-error = 0.44
max-post-error = 0.44

No idea why this is going wrong as it seems to work correctly when generating the gains with similar settings.

As I was not entirely sure where the problem is there is also an [issue on the stimela github](https://github.com/SpheMakh/Stimela/issues/456)

**Comment by JSKenyon** [comment]
@PeterKamphuis As your MS is relatively small, would it be possible to upload it and the .parset you used to Dropbox? That will aid us a great deal in debugging this for you.

**Comment by PeterKamphuis** [comment]
@JSKenyon Well, my dropbox is only 2.5 Gb but I could put it on stills?

**Comment by JSKenyon** [comment]
@PeterKamphuis That is even better. Just let me know where it lives.

**Comment by JSKenyon** [comment]
OK, I think I have tracked down the source of this error: [This line](https://github.com/ratt-ru/CubiCal/blob/5f964be1ce2211417768435e98c93c801be2067e/cubical/solver.py#L560) is at fault. The reason if that for apply-only type gains, there is no model array. This means that gain machines which do some preliminary computation inside the precompute_attributes method (such as the phase-diag solver) may end up trying to do maths on a None. @o-smirnov What do you think is the best way to handle this?

**Comment by JSKenyon** [comment]
@o-smirnov In fact, I see that the model appears several times in the precompute_attributes code (as a result of inheritance). For an apply only gain, we do not require the model. What would be sensible in this case?

**Comment by JSKenyon** [comment]
I have created an issue-315 branch. There is a naive fix implemented on the branch if you want to try it out. You can either clone the repo, checkout the branch and install or alternatively install using:
`pip install "cubical[lsm-support]@git+https://github.com/ratt-ru/CubiCal.git@issue-315"`

**Comment by PeterKamphuis** [comment]
@JSKenyon As far as I can figure out this fixes the problem. Sorry for taking so long to test it. Somehow I missed your later comments.

**Comment by PeterKamphuis** [comment]
@JSKenyon However, on my test set it seems that the solutions are not applied when using xfer-from. Cubical runs fine but when I make an image from the corrected column it is the same as an image from the data column. This is not the case if I make an image after the Cubical run that made the gain tables. This might be an error in my settings but I don't see it.

**Comment by JSKenyon** [comment]
@PeterKamphuis Sorry for the delay. Poking @o-smirnov - as I did not write the original xfer code I am in a little over my head here.

**Comment by PeterKamphuis** [comment]
@JSKenyon  No worries. Paolo Serra doesn't seem to have the issue so we're trying to figure out what is going on there.

**Comment by PeterKamphuis** [comment]
@JSKenyon  Apparently I was running a previous version of stimela so maybe this already got solved. My apologies if so I will test the current stimela as well as the direct cubical master.

**Comment by PeterKamphuis** [comment]
@JSKenyon  It was not the previous version that was causing the problem as it still happens, but it must be something in my settings that is causing the error as when I run in the same way as paolo serra it doesn't occur. I'll close this issue and let you know when I find the wrong setting.
