### ISSUE TITLE
occasional divergence reported in first chunk handled by a given worker

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#334]
Filing this away so I don't forget... running on the A3556 data (Shapley epoch 1), chunk D0T15F0 is giving me different solver behaviour in single-chunk versus full solution mode.

In single-chunk mode (see ``/home/oms/projects/Shapley/selfcal-shap1/phase-only1-redo.cc-out``):

```
INFO      17:32:30 - solver             [19.6/23.0 22.4/25.8 5.6Gb] D0T15F0 chi^2_0 1.015; G: 228/236 ints (252792-510388 EPA) 57/59 ants, MGE 0.0047; noise 1.67, flags: PRIOR:36159348(63.40%) MISSING:966656(1.69%) SKIPSOL:189016(0.33%)
INFO      17:33:03 - solver             [23.0/26.4 25.8/29.2 5.6Gb] D0T15F0 G: 1 iters, conv 0.00%, d/fl 3.39%, max update 0.9726, PGE 0.00267 chi2 0.5309, rel delta 0.9127 max 0.9995, active 51.38%, diverging 30.44%
```

When solving for the full MS (see ``/home/oms/projects/Shapley/selfcal-shap1/phase-only1.cc-out``):

```
INFO      17:00:46 - solver             [x04] [25.6/32.8 28.8/39.1 47.1Gb] D0T15F0 chi^2_0 0.5363; G: 236/236 ints (456684-966656 EPA) 59/59 ants, MGE 0.0047; noise 1.67, flags: PRIOR:36159348(63.40%) MISSING:966656(1.69%) SKIPSOL:189016(0.33%) MAD:14716(0.03%)
INFO      17:01:19 - solver             [x04] [29.0/32.8 32.2/39.1 47.1Gb] D0T15F0 G: 1 iters, conv 0.00%, d/fl 3.39%, max update 0.9716, PGE 0.00267 chi2 0.5279, rel delta 0.01605 max 0.7915, active 76.80%, diverging 0.03%
```

Note in particular the 30% divergence in the former case, which doesn't happen in the latter case.

This is puzzling, as I would definitely expect identical inputs to the solver in both cases.

Even more suspicious is that in the full MS mode, the first seven chunks all show ~30% divergence, while *all* remaining chunks diverge at <1% level. And I'm running 7 solver workers. It almost smells like a worker goes wrong with the first chunk it faces, and works OK after that... but how can that be -- there's not supposed to be any persistent state?

(Probably unrelated to #322, but linking to it here so I can address both at once.)

**Comment by o-smirnov** [comment]
> It almost smells like a worker goes wrong with the first chunk it faces, and works OK after that... but how can that be -- there's not supposed to be any persistent state?

Note to self: theoretically, it could also be that the first tile (and only the first tile) is read incorrectly somehow. What argues against this is that there are 8 chunks in a tile, and the last chunk (D0T7F0) does not show divergence.

This does highlight another wrinkle:

```
INFO      16:41:59 - data_handler       [0.5/1.0 3.6/3.7 0.0Gb]   row chunks yield 91 potential tiles
INFO      16:42:00 - data_handler       [0.6/1.0 3.7/3.7 0.0Gb]   coarsening this to 12 tiles (max 8 chunks per tile, based on 7/0 requested)
```

Why is it using 8 chunks per tile, with 7 workers? This is bad for parallelism -- 7 chunks are solved for in parallel, then 6 workers sit around idle while chunk number 8 is processed. Why is it not picking 7 chunks per tile?

Anyway, I suppose the good news is that it can only get faster and better. :)

**Comment by o-smirnov** [comment]
> Even more suspicious is that in the full MS mode, the first seven chunks all show ~30% divergence, while all remaining chunks diverge at <1% level. And I'm running 7 solver workers. It almost smells like a worker goes wrong with the first chunk it faces, and works OK after that...

Though interestingly, running on A3562 (the other field from this MS), there's no such divergence in the initial chunks. Which sort of undermines the above theory.

**Comment by o-smirnov** [comment]
Definitely a worrying bug. If I run the first seven chunks in parallel like this:

```
gocubical cc-kref.parset --data-ms ../msdir/1562500862_sdp_l0-A3556_corr.ms --sol-jones k --sol-term-iters 20 --out-dir delay1 --out-name a3556 --dist-ncpu 8 --sol-min-bl 100 --log-verbose solver=4 --k-estimate-delays 0 --out-column CORR_K_DATA --data-single-tile 0 --weight-column WEIGHT 
```
All seven show ~30% divergence at the start. If I run the same serially with ``--dist-ncpu 1``, D0T0F0 has 30% divergence, but the next one, D0T1F0 diverges at <1%.

**Comment by o-smirnov** [comment]
OK I see the bug, it's a funny one -- it's in how madmax handles thresholds. The default threshold is something like ``[0,10]``, meaning no madmax at iter 1, and madmax at 10 sigma in subsequent iterations. However, the flagger object kept this list by reference (by reference to the original list in the ``GD`` dict) but treated it as a private object and popped stuff off the front, with the result that after the first madmax invocation in a given worker process, the list became simply ``[10]`` and stayed that way forever, so subsequent chunks unintentionally unleashed madmax from iteration 1.

The reported ~30% initial divergence at iteration 1 is due to RFI or otherwise bad data. From the logs, it's clear that madmax was successfully stomping out the bad visibilities in the subsequent iterations. And once it became accidentally enabled from iteration 1, it killed them outright, so subsequent chunks didn't see that initial divergence at all.

So:

* Unintentionally enabling MadMax from early on was actually a good thing -- it actually does its job, and should be on from iteration 1 by default I reckon

* Dunno if it made much of a difference to the outcome though, since the RFI was quashed in subsequent iterations

* ...but since @bennahugo's made us complain about divergence, it's good to avoid it up front.

**Comment by o-smirnov** [comment]
Yes well, that's pretty much what @landmanbester is suggesting with the robust solver. Need to try that ASAP (but I want to get slopes under control first!)

But in the meantime, flagging flagrant outliers in the residuals is better than trying to solve with them in the pot, IMHO.

**Comment by landmanbester** [comment]
Well, I'm suggesting some hybrid of the two approaches. I think you should do an initial run with the robust solver forcing the degrees of freedom parameter to some low value and possibly keeping the data covariance set to unity for efficiency. Then you can flag the flagrant outliers by clipping weights below some threshold (or using deviation from the median, for example). This should leave only the low-level RFI which you can then handle correctly by doing a full robust calibration run i.e. inferring the optimal number of degrees of freedom and  data covariance

**Comment by o-smirnov** [comment]
OK, now that madmax is consistently flagging away obviously bad (10-12 sigma) stuff, I see divergence reported in 0.1~1% of time/frequency slots. 

Note that madmax takes out individual visibilities -- the divergence is detected on a coarser level, for the time/freq slot as a whole (i.e. all baselines). 

I interpret the residual divergence as RFI flying below Max's threshold on *some* baselines that then causes the whole slot to diverge in aggregate. I'm tempted to just flag those slots. It seems like a good heuristic -- if it's diverging, it means some baselines have non-antenna-based errors. The downside is flagging away some good data, but if it's <1% and gets rid of RFI, then what's there to lose really?

Thoughts?

**Comment by bennahugo** [comment]
Run a smoothing filter through the delays and gains and clip the outliers.
That is what I'm doing with the casa solutions before applying.
