### ISSUE TITLE
Running under Slurm (CubiCal v1.4.4)

### ISSUE THREAD

**Issue by mattyowl** [ratt-ru/CubiCal#352]
I've installed CubiCal v1.4.4 with Montblanc 0.6.1 and the private, development version of DDFacet (https://github.com/cyriltasse/DDFacet; up to date with master). This is installed under Anaconda3. 

I've installed on two machines, an old but huge shared memory machine, and on UKZN's cluster. On both machines if I run gocubical directly, it works. However, when running under slurm (which we have to do on the cluster) then it hangs after running Montblanc. What seems to happen is that gocubical has gone to sleep and will never pick up after Montblanc finishes. If the slurm job isn't killed, it just pretends to keep running.

The slurm script to run the test data is
```
#!/bin/sh
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --mem=64000
#SBATCH --time=47:59:00

source /home/mjh/SETUP_CONDA.sh
export OMP_NUM_THREADS=1

python d147_test.py --ms SUBSET-D147.MS
```

I also tried running on some MeerKAT data - this has all the wrong settings I'm sure but does the same thing (hangs after Montblanc finishes). The slurm script for that is below.

```
#!/bin/sh
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --mem=64000
#SBATCH --time=47:59:00

source /home/mjh/SETUP_CONDA.sh

gocubical --data-ms=XMMXCSJ2215.9-1738.ms --data-time-chunk=1800s --data-freq-chunk=4 --model-list=J2215.lsm.html --dist-ncpu=2 --sol-term-iters=10
```

I know that if I run directly on the cluster head node, CubiCal carries on after running Montblanc, so this has to be slurm related I think.

**Comment by bennahugo** [comment]
This is the same issue as @IanHeywood is experiencing. As far as I can tell slurm screws around with the tmpfs shared memory settings of the worker nodes upon job submission and reduces the amount of memory available. At present there is no fix available, because I cannot find any documentation on slurm on how to disable or control this behaviour. 

The problem affects all software using shared memory (DDFacet, killMS and CubiCal). 

The only workaround is to limit the number of tiles that gets reduced in parallel, check your parset. Here is my working 800MHz dE calibration procedure which is directly controllable through the parallelization parameter as an example workaround. This may help to considerably reduce memory usage, although your solution intervals will ultimately be limited to how much shared memory you have:

https://github.com/ska-sa/vermeerkat/blob/master/vermeerkat/plugins/INTROSPECT/image.py#L517

**Comment by bennahugo** [comment]
I'm interested in whether Torque and other schedulers impose the same limitations. Maybe it is worth investigating them

**Comment by bennahugo** [comment]
That said somebody with better SLURM foo (e.g. your cluster devops) may be able to discover the SLURM configuration error that leads to this

**Comment by mattyowl** [comment]
I haven't had any problems running DDF or killMS under slurm though. They work fine so far as I can tell.

I'm not getting any error message at all from CubiCal (no OSError, as in Ian's case)  - it's just hanging after Montblanc runs.

**Comment by bennahugo** [comment]
It could be that a process still died of an IO error in the montblanc queue and it is just not reported. However, can you try decreasing the tile sizes and number of tiles being processed simultaneously? By default CubiCal is extremely greedy and these parameters almost always need to be lowered considerably. There definitely is a bug in the slurm scheduler where the available shared memory drops to 50%.

**Comment by JSKenyon** [comment]
Out of interest, is it clear if it dies before or after Montblanc has run? I wonder if this is some nasty interaction between Montblanc's threading (via Tensorflow) and CubiCal's multiprocessing. Might be that it only rears its head in this environment.

**Comment by IanHeywood** [comment]
Note that I have never actually invoked Montblanc via CubiCal via slurm. I had to run it in single-CPU mode to get it to go anywhere, at which point it goes nowhere for other reasons.

I'll be testing this on CHPC's lengau cluster due course. That uses PBS, which I think is related to Torque somehow, but I'm quite out of my depth with a lot of this stuff.

> I haven't had any problems running DDF or killMS under slurm though. They work fine so far as I can tell.

I think data volume / number-of-directions plays a part. Some of the ThunderKAT team run DDF / kMS via slurm on the regular IDIA nodes with no trouble, but that's for ~10-15 minutes of MeerKAT data. MIGHTEE-sized imaging jobs  (~10-20 hours of data) tend to get killed sometime during or shortly after the first major cycle, as do killMS jobs on the same when solving for ~10 directions. Number of baselines is obviously a big factor in how big a chunk size can be implemented for all of these things.

I can get jobs to complete on HighMem IDIA nodes if I book them via `salloc`, but if the job scheduler is involved they always seem to fail.

**Comment by mattyowl** [comment]
Ah okay - Montblanc is dying but it seems CubiCal doesn't know it.

The last few lines of the montblanc.log file on the cluster are
```
2020-03-09 11:53:22,783 - INFO - Selected a solver memory budget of 752.0MB given a hard limit of 1.0GB.
2020-03-09 11:53:22,783 - INFO - The following dimension reductions were applied:
2020-03-09 11:53:22,783 - INFO -     ntime: 113 => 34
2020-03-09 11:53:22,839 - INFO - Done feeding 4 descriptors.
2020-03-09 11:53:24,287 - INFO - Enqueueing chunk [  34   68  113    0 1770 1770] on shard 1
2020-03-09 11:53:25,532 - INFO - Enqueueing chunk [   0   34  113    0 1770 1770] on shard 0
```
i.e., Montblanc doesn't get to 'Solution completed'. But then it doesn't tell me that it crashes, either (and it doesn't, when not run under Slurm).

Anyway - it'd be nice if CubiCal could catch when Montblanc crashes and report an error?

**Comment by mattyowl** [comment]
Ok - I think I've solved it (or at least it's running now under Slurm).

My Slurm job script up there only asked for 2 CPUs, because I'm running CubiCal with `--dist-ncpu=2`.

However, after doubling the number of CPUs used in the Slurm script:
```
#SBATCH --ntasks-per-node=4
```

Montblanc is now happy. So, I _think_ CubiCal is using more processes than `--dist-ncpu` suggests, because it seems to launch Montblanc as separate processes (?). But then Slurm prevents it from opening new processes if the number is > number of CPUs Slurm is asked for.

Anyway - I'll wait and see if my jobs complete successfully and then maybe this can be closed. But if this is right, then it could probably be added to the docs somewhere.

**Comment by bennahugo** [comment]
@mattyowl that switch only controlls the solver. Montblanc has its own pool and the DDFacet degridder its own pool. However I don't think this will make it fall over - it just means the pools may potentially thrash for resources in a concurrent processing way, where one thread is swapped for another. I think you are seeing this improvement because you are indirectly making it grab fewer tiles of data simultaneously.

**Comment by bennahugo** [comment]
There are separate switches btw to control those number of threads.

**Comment by o-smirnov** [comment]
I'm a bit vague about how Montblanc (Tensorflow, ultimately) allocates CPUs, @sjperkins or @JSKenyon would have a clearer idea. IIRC, it is only partially under CubiCal's control. Good catch, @mattyowl, this could well be the problem. Could you please post your entire parset/start of logfile?

It occurs to me we also have some CPU pinning features which could inadvertently interfere if enabled, let's make sure this is not happening.

**Comment by mattyowl** [comment]
Ok, I spoke too soon anyway - bumping up the number of tasks in the slurm script enabled it to get past the first Montblanc run, but it then hangs at this stage (last log entry):

```
INFO       - 15:45:26 - main               [0.9/1.0 2.2/2.3 3.5Gb] finished processing tile 1/25
INFO       - 15:45:26 - main               [0.9/1.0 2.2/2.3 3.5Gb] waiting for I/O on tile 2/25
```

It doesn't crash - there are just stopped gocubical processes if I log into the node this is running on. It seems like it still has ~29 Gb free under /dev/shm.

Below are the parset and log for this thing (again, these are probably dumb settings... I'm just trying to get it to run to the end like it does on the non-slurm running machine).

[cc.parset.txt](https://github.com/ratt-ru/CubiCal/files/4307050/cc.parset.txt)
[cc.log](https://github.com/ratt-ru/CubiCal/files/4307051/cc.log)

**Comment by bennahugo** [comment]
@mattyowl please set the following much lower (0 means no limit):
INFO       - 15:34:39 - main               [0.2/0.2 0.7/0.7 0.0Gb]  - max-chunks ........................................ = 0
INFO       - 15:34:39 - main               [0.2/0.2 0.7/0.7 0.0Gb]  - min-chunks ........................................ = 0
and substantially decrease:
time-chunk ........................................ = 1800s

This will significantly reduce your footprint

**Comment by mattyowl** [comment]
@bennahugo I tried your suggestion... it still hangs.

However, I think I've found something else - after the 'waiting for I/O to finish' message, in the slurm.out file I see lines like:
```
2020-03-17 14:30:02     INFO            Process 27836: waiting for write-lock on file /data/mjh/MeerKAT/XMMXCSJ2215.9-1738.ms/table.lock
```
and
```
2020-03-17 15:10:07     INFO            Process 9045: waiting for write-lock on file /data/mjh/MeerKAT/XMMXCSJ2215.9-1738.ms/table.lock
```

These don't appear in `cubical.cc-out/cc.log`

**Comment by o-smirnov** [comment]
That happens when another process on the system has the same MS open. Something like

```
lsof | grep XMMXCSJ2215.9-1738.ms/table.lock
```

will usually show the culprit.

**Comment by mattyowl** [comment]
I've not been running CASA and lsof doesn't work on our cluster apparently.

However, I have managed to get CubiCal to complete successfully under slurm - I deleted the table.lock file and ran gocubical without specifying --dist-ncpu. I think it then ran on only one CPU, but in any case it completed the job. I'll see if I can get it to run properly with more CPUs.

**Comment by mattyowl** [comment]
Ok - I got it running on 20 CPUs and it completed successfully. Maybe this was just the memory thing (though no idea about the table.lock file issue as it should only have been me using the measurement set so far as I know). I've attached my slurm script below for reference - again, no claims that any parameter settings used are sensible - this was just to get up and running. Thanks for all your help.

[cubicaltest20.sh.txt](https://github.com/ratt-ru/CubiCal/files/4348241/cubicaltest20.sh.txt)

**Comment by JSKenyon** [comment]
@mattyowl I am really happy that you managed to get it running - apologies that I was not of more use. I have literally zero experience with Slurm.

Regarding your lock issue - that is just one of the many exciting problems which can develop in an MS. It most often happens when a run is interrupted/fails unexpectedly. So even though you were the only person using the MS, your previous failed/aborted runs could have put your MS in a whacky state. Fortunately deleting the lock usually remedies the situation.
