### ISSUE TITLE
Solution interpolation code should allow for (reasonable) extrapolation

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#357]
The bug in #336 highlights a deficiency of the current interpolation code. Firstly, there are things like https://github.com/ratt-ru/CubiCal/issues/336#issuecomment-601086600. This is clearly the edge solutions not extrapolating over [what I presume is] the first half of the first low-res interval, and the last half of the last low-res interval. 

I think the standard numpy functions I'm using are simply refusing to extrapolate, which is a PITA.

More worrying is stuff like https://github.com/ratt-ru/CubiCal/issues/336#issue-556460986, especially the fourth plot. Those black triangles, and black bands around the side, show interpolation failing in a way I don't expect (especially given it's asked to interpolate onto the highest resolution in this instance!) @PeterKamphuis, if you have that GMRT MS+solutions+parset handy, I would appreciate a copy.

**Comment by PeterKamphuis** [comment]
@o-smirnov I'll test the branch tomorrow. Just to ease you mind somewhat the black bands and triangles in the fourth plot had already disappeared the last time I tested, as reported here https://github.com/ratt-ru/CubiCal/issues/336#issuecomment-598225031 and thus might have been related to the casa-core issue reported by @bennahugo. That test looked the same as the third plot in https://github.com/ratt-ru/CubiCal/issues/336#issue-556460986 after the roll back of casacore.

**Comment by o-smirnov** [comment]
OK I pushed a fix to ``issue-357``. This now extrapolates the time axis at least:

![image](https://user-images.githubusercontent.com/6470079/77776416-a8d12a80-7056-11ea-8d87-6209deb9989e.png)

However, inter/extra-polation in time+freq is a different code path, and this is currently untested. I'd therefore love to have a test tarball from @PeterKamphuis to check this.

**Comment by PeterKamphuis** [comment]
@o-smirnov I'm sorry for the delay in getting you the test set but uploading is a $%^&!!!! from home. So far I have been looking at a 4 hr upload, a kernel panic on my mac and a crashed external disk with all the work for a almost finished paper. All is fixed now and hopefully I can send you a location in 40 min (according to google). In the meantime I'll try the new branch.

**Comment by PeterKamphuis** [comment]
So just tried the xfer-from with interpolation on the branch issue-357 and that crashed with

Exiting with exception: ValueError(x and y must have equal lengths for non rectangular grid)
 concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/peter/GitHub/CubiCal/cubical/solver.py", line 847, in run_solver
    gm = vdm.gm = gm_factory.create_machine(vdm.weighted_obser, n_dir, n_mod, chunk_ts, chunk_fs, label)
  File "/home/peter/GitHub/CubiCal/cubical/machines/abstract_machine.py", line 912, in create_machine
    gm._load_solutions(self._init_sols)
  File "/home/peter/GitHub/CubiCal/cubical/machines/abstract_machine.py", line 630, in _load_solutions
    sols[label] = sol = db[name].reinterpolate(**grids)
  File "/home/peter/GitHub/CubiCal/cubical/database/parameter.py", line 610, in reinterpolate
    filled_array, bounds_error=False)
  File "/home/peter/GitHub/Cubical-venv/lib/python3.6/site-packages/scipy/interpolate/interpolate.py", line 225, in __init__
    "x and y must have equal lengths for non rectangular grid")
ValueError: x and y must have equal lengths for non rectangular grid
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/peter/GitHub/CubiCal/cubical/main.py", line 550, in main
    stats_dict = workers.run_process_loop(ms, tile_list, load_model, single_chunk, solver_type, solver_opts, debug_opts, out_opts)
  File "/home/peter/GitHub/CubiCal/cubical/workers.py", line 214, in run_process_loop
    return _run_multi_process_loop(ms, load_model, solver_type, solver_opts, debug_opts, out_opts)
  File "/home/peter/GitHub/CubiCal/cubical/workers.py", line 300, in _run_multi_process_loop
    stats = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: x and y must have equal lengths for non rectangular grid


load-from runs fine.

**Comment by o-smirnov** [comment]
OK, I'll need a test MS now...

Cheers,
Oleg

---
Sent from my phone. Quality of spelling inversely proportional to finger
size.

**Comment by o-smirnov** [comment]
Well I did say the 2D interpolation codepath was untested... and the GMRT data was exactly the test I was missing.

I've pushed a fix, looks OK now. This is baseline 0-1 after running ``xfer-from.parset`` on the test that @PeterKamphuis so kindly put together for me:

![image](https://user-images.githubusercontent.com/6470079/77799223-02e4e680-707d-11ea-9c27-70614f17980f.png)

@PeterKamphuis, it does need a bit more battle-harding now -- would you please make sure the results are to first order consistent with load-from?

**Comment by PeterKamphuis** [comment]
@o-smirnov Yes looks good to me now. I'll make some images later to truly double check.

I did get the following warning
 ComplexWarning: Casting complex values to real discards the imaginary part
  kx=kx, ky=ky, s=0.0)

I assume it can be ignored?

**Comment by PeterKamphuis** [comment]
I made dirty images of the field with both the calibration applied from load-from and xfer-from  and they are practically the same.
![Compare_load_xfer](https://user-images.githubusercontent.com/11264005/77891477-50c24000-7271-11ea-8cd8-54cbcc6909d3.png)

With the color scale and white contours from Load-from and the black contours from xfer from.
Statistics for the purple square are (from Casa):
load-from in Jy/beam:               /              xfer-from in Jy/beam     
     RMS: 1.610522e-3         /                   RMS: 1.644439e-3
     Mean: -1.129284e-5       /                    Mean: -6.135530e-5
     Min: -4.648407e-3         /                     Min: -4.633886e-3
     Max: 6.172432e-3         /                     Max: 6.213652e-3

Full image:
Load-from in Jy/beam         /                     xfer-from in Jy/beam
     RMS: 2.442425e-3          /                   RMS: 2.471148e-3
     Mean: 5.786144e-6          /                  Mean: 5.968290e-6 
     Min: -9.283315e-3            /                  Min: -9.835174e-3
     Max: 5.808980e-2            /                  Max: 5.773183e-02 

To me it seems the differences are small enough to be explained by the fact that xfer-from should interpolate over some missing solutions.

@o-smirnov let me know if you want to see anything else.

**Comment by o-smirnov** [comment]
> I assume it can be ignored?

I think so, but let me double-check before I close this issue (and pop the bubbly).
