### ISSUE TITLE
memory use grossly underestimated in apply-only mode

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#388]
See discussion (and esp. attached log) in https://github.com/caracal-pipeline/caracal/issues/1198. 

The estimate for the I/O worker seems especially off...

**Comment by JSKenyon** [comment]
I might need access to some data @o-smirnov - fixing this is likely possible, but a reproducer would be good.

**Comment by o-smirnov** [comment]
I'm downloading a modest 2TB test case for us as we speak...

**Comment by JSKenyon** [comment]
Very modest. Paltry even.

**Comment by o-smirnov** [comment]
OK @JSKenyon I have a test for you. Go to simon, ``/home/oms/projects/cc-test`` (or via /net), and see parset within. You probably don't want to copy a 4TB MS, so I've given you write-access. I think.

I've disabled PA rotation and fixed a bug with how the number of workers is allocated (you want to run with 4 workers here, to match the number of chunks). This makes the RAM footprint a bit more manageable:

```
INFO      14:02:56 - gain_machine       [x04] [43.5/220.8 42.8/216.7 24.9Gb] D0T3F0: interpolating G:gain from zoom-g-phase-gains-1-1588316462_sdp_l0-NGC1365-corr_avg.parmdb
```

...which for a tile of ~100k rows and 13k channels is not unreasonable (that's 2*10^9 complex visibilities per tile just raw data...) But the memory estimates seem grossly off:

```
INFO      14:00:35 - wisdom             [1.0 1.0 0.0Gb] Per-solver (worker) memory use estimated at 0.45GiB: 0.09% of total system memory.                                                      
INFO      14:00:35 - wisdom             [1.0 1.0 0.0Gb] Peak I/O memory use estimated at 0.37GiB: 0.07% of total system memory.                                               
INFO      14:00:35 - wisdom             [1.0 1.0 0.0Gb] Total peak memory usage estimated at 2.19GiB: 0.43% of total system memory.                                            
```

**Comment by JSKenyon** [comment]
This was nothing too mysterious. `n_dir` was being taken from the model, which doesn't exist in the transfer-only case. Fixed in #394. Please review (it's a half-line of code) when you have a moment @o-smirnov. 

Note that the wisdom will overestimate the memory in this case as there is no solve and thus no intermediary arrays are created.

For reference, with my fix:
```
INFO      09:36:06 - main               [1.0 1.0 0.0Gb] multi-process mode: 4+1 workers, single thread
INFO      09:36:06 - wisdom             [1.0 1.0 0.0Gb] Detected a total of 503.81GiB of system memory.
INFO      09:36:06 - wisdom             [1.0 1.0 0.0Gb] Per-solver (worker) memory use estimated at 78.82GiB: 15.65% of total system memory.
INFO      09:36:06 - wisdom             [1.0 1.0 0.0Gb] Peak I/O memory use estimated at 113.74GiB: 22.58% of total system memory.
INFO      09:36:06 - wisdom             [1.0 1.0 0.0Gb] Total peak memory usage estimated at 429.04GiB: 85.16% of total system memory.
``` 

Is that vaguely acceptable?

**Comment by o-smirnov** [comment]
@JSKenyon, shm memory footprint is lumped into the I/O worker estimate, I assume?

Let's see, for this very test case, reported overall use peaks at 340Gb (as counted by USS/PSS metrics, see https://psutil.readthedocs.io/en/latest/#psutil.Process.memory_full_info), with shm at 80Gb. One thing I'm not clear about, even after reading the psutils docs, is shm included in PSS? Reading the numbers, I sort of suspect that not. (Otherwise PSS would not be following USS so closely). In  which case 340+80 = 420 = very close.

On the other hand, peak USS is reported at ~47Gb for the I/O worker and ~44Gb for a solver worker. Which is only 223 Gb altogether... well short... but perhaps this is because a worker can only check on memory use when a log message is being printed, so any temporary allocations that come and go in between calls to the logger would go unnoticed?

Geez, who knew that accounting for gigabytes would be so difficult...

**Comment by JSKenyon** [comment]
If I remember correctly, I think I generated my heuristics using the peak values. As you say, the log message only knows the memory usage when it is invoked, so may not be an accurate reflection of peak usage. Additionally, in apply only I would expect no JHJ or JHR matrices to be formed. These (or their intemediaries) are roughly the size of the model once it is in CubiCal format. As such, I would be really surprised if the estimate was accurate in this case. 

Regarding shared memory, I am no sure whether it is tracked in psutil. I guess I has always assumed so, but I don't know for certain. My heuristics were generated by running memory_profiler, which I believe does pick it up.

**Comment by o-smirnov** [comment]
OK, but in the wisdom estimates, which estimate includes the shm footprint? I would assume the I/O one?

**Comment by JSKenyon** [comment]
Yes, it is the IO. It is where the data “persists”.
