### ISSUE TITLE
Default of correct-dir=-1 actually corrects towards *last* dE

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#390]
The intention was for ``correct-dir=-1`` to apply only the inverse DI terms when correcting the data. This is the default in the parset.

However it seems the code (interval_gain_machine) expects a None in this scenario, not -1.

-1, rather, causes the inverse of the last DD term to be applied. This is not what we want, generally.

**Comment by o-smirnov** [comment]
Yeah @SpheMakh check if you had it set to -1 when peeling in the NGC4993 field... On the bright side you can have much better images. :dancers:

**Comment by SpheMakh** [comment]
At this point, I actually hope I did!

**Comment by SpheMakh** [comment]
But I don't have the logs anymore, I have to redo the reduction and hopefully, there'll be an improvement.
