### ISSUE TITLE
modify --dist-safe to be a float fudge factor

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#399]
I suggest changing ``--dist-safe`` to a float, with the semantics of "fraction of memory beyond which we refuse to run", with 0 disabling checking. Default of 1 means 100%.

Rationale: someone might want to run with 0.5 (to be neighbourly to other node users). And someone else might observe that in their particular regimes, memory use is consistently overestimated, and decide to run with 1.5 or 2.

This proposal keeps backward compatibility, and trivially allows such cases.

**Comment by JSKenyon** [comment]
@o-smirnov I have made a branch and added this functionality. Will make a PR shortly.

**Comment by JSKenyon** [comment]
Added in #401,
