### ISSUE TITLE
one cross correlation product in measurement set

### ISSUE THREAD

**Issue by Kincaidr** [ratt-ru/CubiCal#412]
Hi,

I am trying to test cubical on my ms via this simple command:

 gocubical  --data-ms A2384.SP2B.CAL.RR.ms --data-column DATA --out-column CORRECTED_DATA --model-ddes auto --g-type phase-diag --data-freq-chunk 100 --data-time-chunk 40 --dist-ncpu 30 --model-list MODEL_DATA

The resulting error is:

![image](https://user-images.githubusercontent.com/53697426/99182054-3d4de180-273b-11eb-9012-f560239fb2b4.png)

This MS has only one cross-correlation(Stoke I), which is what is giving cubical the problem.

Thanks,
Robert

**Comment by o-smirnov** [comment]
Yeah I'm not sure what a quick workaround would be. How did you end up with only one correlation anyway? Any chance of getting back to the original data and extracting both corrs?

**Comment by Kincaidr** [comment]
This is an issue with SPAM, which was used in the data reduction of the gmrt data.  SPAM has combined both RR and LL in to I. I could use Caracal to the avoid issue altogether, but i was told SPAM works best for gmrt data. I therefore have to find a way to separate them.

**Comment by JSKenyon** [comment]
The path of least resistance might be to manhandle your MS such that each data-like column contains two correlations and just copy the I values into both. I can try make some time to look over the code, but I suspect that supporting this everywhere would be a non-trivial change.

**Comment by Kincaidr** [comment]
With help of ulrich, issue has been solved.

You basically have to change all columns used by cubical by removing the data(remember to store removed data in a variable before removing) and then adding them to new columns with the correct shape,which is done by using. After obtaining the correct shape, you just make duplicates of the data for the 2 correlations.

The workers used for this are: msutilis and pyrab.tables

The detailed explanation for each column is explained below:


For the DATA column we can see that:

![image](https://user-images.githubusercontent.com/53697426/99259261-685f3080-2822-11eb-9bd7-90b551ee3447.png)


The last command: data.shape gives us (10,42,1); this 1 must be changed to 2. We do this with the use of the addcol command from msutils:

![image](https://user-images.githubusercontent.com/53697426/99268046-5931b000-282d-11eb-8794-eb3cc3dfa504.png)

Now we make duplicate paits of the data for the 2 correlations:


Now since for the DATA column, the name is arbitrary(--data column cubical command can take any value) we did not have to remove this column; instead we just added a new column called "NEW_MODEL_DATA" . So when issuing the cubical command we will just have --data column "NEW_MODEL_DATA" instead of --data column "DATA". Since the latter will have the incorrect shape.

Now that we have the correct shape(10,42,2), we have to match this up with the correlation. This is found in the polarization tables of the MS:

![image](https://user-images.githubusercontent.com/53697426/99264070-b119e800-2828-11eb-99e8-e91e5d497425.png)

Check for correct correlation:

![image](https://user-images.githubusercontent.com/53697426/99264157-c727a880-2828-11eb-8a07-6ed27330a9ba.png)

A run of cubical using: gocubical --data-ms A2384.SP2B.CAL.RR-2.ms --data-column NEW_DATA --out-column NEW_CORRECTED_DATA --model-ddes auto --g-type phase-diag --data-freq-chunk 100 --data-time-chunk 40 --dist-ncpu 30 --model-list NEW_MODEL_DATA

will give:


![image](https://user-images.githubusercontent.com/53697426/99264604-592fb100-2829-11eb-855b-895be092e680.png)

This is because the other columns used by Cubical do not match: Below i show this for the 2 columns WEIGHT and WEIGHT_SPECTRUM


![image](https://user-images.githubusercontent.com/53697426/99265975-f7704680-282a-11eb-8a46-754ed61b06d3.png)





We see the 1 must also be changed to a 2 in these columns. 

Same for FLAG
![image](https://user-images.githubusercontent.com/53697426/99264838-a3b12d80-2829-11eb-958b-d45553821a36.png)

So starting with WEIGHT and WEIGHT_SPECTRUM we remove them(remember to save them as variables as was done in the screenshot above FLAG screenshot). We cannot just add new columns like was done with DATA, since cubical will directly look for these names, they are not arbitrary. :

![image](https://user-images.githubusercontent.com/53697426/99265223-1fab7580-282a-11eb-8ea0-3db877c7474c.png)


and now we add using addcol from msutils. For WEIGHT_SPECTRUM

![image](https://user-images.githubusercontent.com/53697426/99266444-706f9e00-282b-11eb-8d88-59c89fc8e396.png)


Due to the shape form of WEIGHT: (....,1) (compared to (...,...,1) of WEIGHT_SPECTRUM. We must add WEIGHT like:

![image](https://user-images.githubusercontent.com/53697426/99266319-4e761b80-282b-11eb-8c6d-a677e99c9544.png)

Now check the shape: 

![image](https://user-images.githubusercontent.com/53697426/99266649-a876e100-282b-11eb-8eec-6882a238ac6d.png)

Once the shape is corrected. 

![image](https://user-images.githubusercontent.com/53697426/99267347-83cf3900-282c-11eb-8e41-dc4eb8992780.png)

**Comment by o-smirnov** [comment]
Cool, good job figuring it out!
