### ISSUE TITLE
Python 2 support going one... going two... going 2.7... 

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#425]
I see we're still clinging to py2 support, like an old mole-eaten blanket. Nothing wrong with that, except I had to jump through some hoops in https://github.com/ratt-ru/CubiCal/pull/424 to retrofit.

Note however that the current py2 version fails for me with:
```
INFO      13:11:47 - main               [4.2 11.6 0.0Gb] Exiting with exception: AttributeError('module' object has no attribute 'set_num_threads')
 Traceback (most recent call last):
  File "/home/oms/projects/CubiCal/cubical/main.py", line 544, in main
    max_workers=chunks_per_tile)
  File "/home/oms/projects/CubiCal/cubical/workers.py", line 131, in setup_parallelism
    numba.set_num_threads(int(nthread))
AttributeError: 'module' object has no attribute 'set_num_threads'
```
Perhaps this is not caught in testing.

Do we fix this, or do we just drop py2 and move on? Opinions solicited.

**Comment by bennahugo** [comment]
The python 2 support is solely there at your discretion. It is now a year
since sunset. If people haven't moved on, I think they need a kick in the
but!

**Comment by JSKenyon** [comment]
Anything which reduces maintenance is fine by me. As Ben mentioned, 2.7
should be allowed to go extinct.

**Comment by o-smirnov** [comment]
The chorus of support for poor little py2 is deafening! OK let's take it out as part of #424.

**Comment by KshitijT** [comment]
> The chorus of support for poor little py2 is deafening! OK let's take it out as part of #424.

I'll miss py2. :'(

**Comment by cyriltasse** [comment]
I like Python 3 with the clearer imports but I don't get why it's so complicated with strings... @KshitijT even I have abandoned my makefiles... :))

**Comment by o-smirnov** [comment]
> I'll miss py2. :'(

Ah but will you miss it enough to have your friends suffer the continued support? :grimacing: 

And yes the unicode thing is a disaster. That's what happens when colonialism fails!

**Comment by KshitijT** [comment]
> Ah but will you miss it enough to have your friends suffer the continued support? ￼
 
Of course. :P
