### ISSUE TITLE
apply gains to autocorrs 

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#436]
@bennahugo has requested that we apply gains to autocorrelations when forming corrected data. 

At the moment we zero them "as a precaution" [here](https://github.com/ratt-ru/CubiCal/blob/master/cubical/data_handler/ms_tile.py#L435), but I see no reason not to flag them with FL.SKIPSOL instead (as we do with baseline length selections right now) to have them ignored yet corrected.

**Comment by JSKenyon** [comment]
I have taken a brief look. While I do think that it will probably be ok to do as you suggest, it will also require changes to the `compute_corrected` kernels. At present, they loop over baseline with a strict `p < q` approach. We will need them to include `p == q`. If you think this is worthwhile, I can try to implement something tomorrow.

**Comment by JSKenyon** [comment]
This slipped my mind - should I give it a shot @o-smirnov?

**Comment by o-smirnov** [comment]
Yes, please! I am buried in admin at the moment. 

You need to fix the kernels, take out the "precaution", and set ``FL.SKIPSOL`` on them instead.

**Comment by JSKenyon** [comment]
@o-smirnov @bennahugo See #437. I have tried it out locally and nothing seems to burst into flame.

**Comment by o-smirnov** [comment]
> and nothing seems to burst into flame.

That's my definition of a successful pipeline run!

**Comment by o-smirnov** [comment]
Also when I don't get arrested.
