### ISSUE TITLE
Deprecation of the Regions parser

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/CubiCal#455]
Need to fix:
```
WARNING: AstropyDeprecationWarning: The DS9Parser class is deprecated and may be removed in a future version.
        Use `regions.Regions.parse` instead. [cubical.degridder.DicoSourceProvider]
WARNING:astropy:AstropyDeprecationWarning: The DS9Parser class is deprecated and may be removed in a future version.
        Use `regions.Regions.parse` instead.
```

**Comment by o-smirnov** [comment]
Yeah I just moved breizorro to regions, it's simple: https://github.com/ratt-ru/breizorro/blob/main/breizorro/breizorro.py#L226

**Comment by bennahugo** [comment]
will change to ```regions.Regions.read(filename) ``` which may autodetect the format from the magic string as discussed. The ```.parse``` does not for some reason - at least not in the last release version for python 3.6

**Comment by bennahugo** [comment]
done
