### ISSUE TITLE
Null-v: Key doesn't exist

### ISSUE THREAD

**Issue by AKHughes1994** [ratt-ru/CubiCal#473]
Hello, 

First of all, sorry if this is a silly question, 

When trying to run a K-slope calibration run I get this error that kills the process

` Traceback (most recent call last):
  File "/home/ubuntu/VirtualEnvironments/CubiCalEnv/lib/python3.9/site-packages/cubical/main.py", line 457, in main
    null_v=GD["model"]["null-v"])
KeyError: 'null-v'`

I'm not exactly sure how to debug this issue, so I was hoping for some advice on where to begin. 

Thanks,
Andrew

P.S. I've attached my parset 
[DI_bb2.txt](https://github.com/ratt-ru/CubiCal/files/11643337/DI_bb2.txt)

**Comment by o-smirnov** [comment]
Try adding 
```
null-v = 0
```
To the ``[model]`` section of your parset. This is a recent feature -- perhaps you're using a parset you made for an older version (if so, this means we mucked up the version transition... that key should be there by default...)

**Comment by AKHughes1994** [comment]
Adding that term changes the error to

` Traceback (most recent call last):
  File "/home/ubuntu/VirtualEnvironments/CubiCalEnv/lib/python3.9/site-packages/cubical/main.py", line 453, in main
    ms.init_models(models, weights, fill_offdiag_weights=GD["weight"]["fill-offdiag"],
TypeError: init_models() got an unexpected keyword argument 'null_v'
`

**Comment by AKHughes1994** [comment]
I'm guessing for some reason it is reading null-v in as null_v.

**Comment by JSKenyon** [comment]
Hi @AKHughes1994! I am trying to reproduce the error. Could you possibly try and run using Python 3.8? I suspect that the problem is only in 3.9+. Not sure how long it will take me to find it.

**Comment by JSKenyon** [comment]
Ah, after some head scratching I have managed to reproduce. This bug is in the release version on PyPI. You can install from the master branch on the repo and things should work - I will investigate the root cause.

**Comment by AKHughes1994** [comment]
I can confirm this fixed the issue on my end. Thanks!
