### ISSUE TITLE
add support for multiple weighted models

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#5]
This one is somewhat speculative but should form the research component of @JSKenyon's PhD. I would like to try simultaneous calibration using different sky models. That is, you may have sky models derived from the sky on different scales -- for example, one model carries information on shorter baselines, the other one on longer baselines. For various reasons, these are not always easy to reconcile into a single image-domain model, so I suggest an alternative approach.

Let's say you have N models, M_1 through M_N (by models I mean model visibilities -- derived from Montblanc, or from an MS column, or some other way). Each model has an associated set of model weights, W_1 ... W_N, one weight per visibility (similar to data weights in #1). What you do is, for every visibility you now form N equations rather than 1 -- and to form the Jacobian, you sum over these N equations. The equations are weighted using the model weights, renormalized to the data weight (that is, normalized such that W_data = W_1+W_N).

I realize this sounds vague so let's discuss F2F.

Putting this into R1 since I predict we're going to need to play with it quite a bit, so the sooner we have a prototype, the better.

**Comment by o-smirnov** [comment]
Bumping this up as it's becoming needed. In fact, a more flexible way of specifying multiple models and directions is needed. I propose the following:
```
--mod-model model1,model2,...
--mod-weight weight1,weight2,...
```
where commas separate multiple models. Each individual model may be composed of one or more directional models:
```
modelN := dirmodel1:dirmodel2:...
```
Each directional model may be a sum of one or more submodels:
```
dirmodelN := submodel1+submodel2+...
``` 
Each submodel may be either a column name, or an LSM filename with an optional ``@tag`` suffix:
```
submodelN := column_name|lsm_filename|lsm_filename@tag
```
If a tag is present (e.g. ``foo.lsm.html@dE``), then the tag is used to separate the LSM into directional components. In the case of submodels being summed, all the untagged sources (and columns) are associated with the 0 direction.

Thus,
```
--mod-model MODEL_DATA+foo.lsm.html@de:DIRMODEL_DATA,OTHERMODEL_DATA
```
specifies two models. The first one contains multiple directions: (a) MODEL_DATA column plus untagged sources in foo.lsm.html, (b) dE-tagged sources in foo.lsm.html, and (c) DIRMODEL_DATA column. The second model consists of the OTHERMODEL_DATA column and is entirely associated with direction 0.

Note that this supersedes the ``--mod-lsm`` and ``--mod-column`` options. The ``--mod-ddes`` option is obviated (from the model specification it is clear whether directions exist or not), but we may want to retain an explicit option to disable DD solutions anyway.

**Comment by o-smirnov** [comment]
An alternative is, instead of separating models by commas, to define multiple options:
```
--mod-1 model1
--mod-2 model2
...
```
where each model is as defined above. Not sure I have a preference.

**Comment by IanHeywood** [comment]
Can I confirm that the --model-list parameter that has now replaced --model-lsm and --model-column, and accepts an input that is akin to:

```
--mod-model MODEL_DATA+foo.lsm.html@de:DIRMODEL_DATA,OTHERMODEL_DATA
```

?

I'm having trouble picking apart this example. From the formatting descriptions that precede it, and the description that follows it, I would expect it to read:

```
--mod-model MODEL_DATA+foo.lsm.html:foo.lsm.html@de:DIRMODEL_DATA,OTHERMODEL_DATA
```

The example says there are three models that have directional solutions (a), (b) and (c), but there are only two colons in the first part.

I'm also guessing the model order (comma separated) follows the Jones chain ordering. Is that correct?

**Comment by o-smirnov** [comment]
OK, so firstly the comma separated models have nothing to do with Jones chains. They just give you the capability to fit multiple models to the same data (and same gains) simultaneously, using the same Jones chain for all models, but potentially different weights (think e.g. a low-resolution and a high-res model, appropriately weighted, so that the low-res model dominates the short spacing solutions, while the high-res model dominates the long ones).
 
Now as for the examples. One thing I didn't quite explain properly is that the "@dE" form implicitly introduces extra directions, according to the LSM contents. 
```
--mod-model MODEL_DATA+foo.lsm.html@dE:DIRMODEL_DATA,OTHERMODEL_DATA
```
Let's say you have 5 dE clusters in foo.lsm.html. The above then actually defines *seven* dE terms for the first model: 

* one for MODEL_DATA plus all sources in foo.lsm.html that do not have a dE tag

* 5 for the 5 dE clusters in the LSM

* one more for DIRMODEL_DATA. 

Arguably, the first dE term should be made un-solvable and fixed to unity -- we've had arguments with @JSKenyon about this -- in practice it will make little difference. The second model just has OTHERMODEL_DATA, associated with the first dE term.

If you look in the log/console output, it will give you a break-down of what each model and direction consists of. Always a good idea to check this, to make sure it's doing what you expect it to do.

Now,
```
--mod-model MODEL_DATA+foo.lsm.html:foo.lsm.html@dE:DIRMODEL_DATA,OTHERMODEL_DATA
```
is very likely incorrect usage. As it is, it defines two models. The second one is the same, OTHERMODEL_DATA. The first one now has 8 directions:

* direction 0: MODEL_DATA plus all the sources in foo.lsm.html (regardless of tags)

* direction 1: all the untagged sources in foo.lsm.html (so now they appear in the RIME twice, which is the wrong part of this scenario)

* directions 2-6: the five dE clusters in foo.lsm.html

* direction 7: DIRMODEL_DATA

So you probably don't want to use the same LSM twice! Two more interesting examples:
```
--mod-model foo.lsm.html@dE:bar.lsm.html@dE
```
will define:

* one direction for all the untagged sources of foo.lsm.html

* one direction for all the untagged sources of bar.lsm.html

* a bunch of directions for the dE-tagged sources in both models, where clusters with a matching dE tag in both models will be associated with the same direction

Finally,
```
--mod-model foo.lsm.html@dE+bar.lsm.html@dE
```
will define:

* one direction for all the untagged sources of foo.lsm.html plus all the untagged sources of bar.lsm.html

* a bunch of directions for the dE-tagged sources in both models, where clusters with a matching dE tag in both models will be associated with the same direction

Hopefully, this is clearer -- and feel free to suggest improvements or alternatives. I just whipped up this scheme last week, so I'm quite open to revising it.

(Just realized there was a small bug in the code, so I pushed a fix to ``ifr-gains``).

**Comment by IanHeywood** [comment]
Thanks for your patience and extensive response... But aren't you supposed to be on vacation?! 

I see my mistake now. So if I've understood:

- The commas separate different models (with optionally different weights)

- Within each model the colons impart different directions

As a further example, let's say I've got a model image which I divide into quarters like a pie, and use each slice to predict visibilities into MS columns MODEL1, MODEL2, MODEL3, MODEL4.

If I wanted to solve four these four models with a direction each, I have no need for a comma, right?

--mod-model MODEL1:MODEL2:MODEL3:MODEL4

**Comment by o-smirnov** [comment]
Yep, exactly right.

**Comment by o-smirnov** [comment]
NB. The option is now called ``--model-list``.
