### ISSUE TITLE
Getting acess to the new repository 

### ISSUE THREAD

**Issue by ulricharmel** [ratt-ru/CubiCal#65]
Hi. I have made few changes on the robust solver. I don't know which settings I need to make to be able create a pull request using the new CubiCal  repository. Is there something I have to change in my settings or I need to clone the new repository to be able to create pull requests.

**Comment by o-smirnov** [comment]
I think Github redirects automatically. But you cal also change your ``CubiCal/.git/config``, just replace ``JSKenyon/CubiCal`` with ``ratt-ru/CubiCal`` in the origin setting. If you have problems pushing after that, tell me, it's probably just a permissions setting.

**Comment by ulricharmel** [comment]
I think it had to do because my forked of the repository was private, so it became a stand alone repository after the main repository went public. I had to re-forked and delete my current repository to fixed that.
