### ISSUE TITLE
need option to select solvable data subset

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#69]
This is distinct from the current ``--sel-taql`` option. The latter selects an overall data subset. A common use case is to solve for gains using a subset of the baselines (e.g. only the longer baselines), but then applying those solutions to all baselines. 

This should be easy to add in: I'll just flag the "excluded" rows with FL.PRIOR. This will cause the solver to ignore them, but residual and corrected visibilities will be computed anyway. We just must make sure that FL.PRIORs are not propagated into the output flags (which they shouldn't be!)

The options shall be called ``--sol-subset`` (for an arbitrary TaQL expression) and ``--sol-min-bl``, ``--sol-max-bl``.

**Comment by IanHeywood** [comment]
Was just about to request this!

Saves an extra load-and-apply operation. Would be a nice feature for MeqTrees too... :)

**Comment by o-smirnov** [comment]
Working on it as we speak. But surely MeqTrees already has this (at least in stefcal)?

**Comment by IanHeywood** [comment]
I know about ms_sel.ms_taql_str for calibrating on a subset, but doesn't that exclude the data not in the subset at the apply stage?

**Comment by o-smirnov** [comment]
Calcio-stefcal also has the ``calibrate_ifrs`` option -- this takes a subset of the ``ms_sel.ms_taql_str`` subset for calibration purposes.

**Comment by IanHeywood** [comment]
Ah, thanks!

So I can use ms_sel.ms_taql_str to select say a group of channels, and then set 

```
calibrate_ifrs = >200
```

to exclude baselines below 200 m from the solve?

PS: Sorry for hijacking this issue.

**Comment by o-smirnov** [comment]
But wait, the channel selection is a separate option. TaQL selects a subset of rows. But yes, that's exactly the idea.

No hijacking, discussion belongs here as it's exactly the same feature.

**Comment by IanHeywood** [comment]
Indeed, I used ms_sel.ms_channel_start / end for that purpose, but that aside I understand what's going on now! Field selection would have been a better example... Cheers.

**Comment by IanHeywood** [comment]
Hang on, is there an equivalent way to select channel ranges in CubiCal, without having to artificially insert SPW boundaries? Can't see such options in the parset or docs...

**Comment by o-smirnov** [comment]
Ha, what an embarrassing omission... I knew we were forgetting something....

**Comment by o-smirnov** [comment]
This, along with #73 and #68, has been implemented in the ``ifr-gains`` branch. Would either of @IanHeywood or @SpheMakh care to give it a test drive before we merge into master?

**Comment by IanHeywood** [comment]
Please see https://github.com/ratt-ru/CubiCal/issues/73

**Comment by o-smirnov** [comment]
Crap, I realize I've implemented this wrong. @IanHeywood, this may explain your odd min-bl/max-bl experiences. 

Internally, it currently flags the data that needs to be ignored in the solve. Unfortunately, this also means that it also zeroes the data/model arrays at those points -- meaning the corrected data for non-solvable visibilities comes out all wrong!

**Comment by o-smirnov** [comment]
Following discussions with @SpheMakh, note to self: we need to zero the flagged/non-selected data and model (for the summation in the update rules to work properly), but when applying gains, we need to apply them to the non-zero'ed data. Therefore, the nulling step in data_handler should be moved to the solver, and should only be applied to the weighted data/weighted model. If we do it this way, then even flagged data will get the gains applied to it in the correction step.
