### ISSUE TITLE
don't enable cython by default

### ISSUE THREAD

**Issue by gijzelaerr** [ratt-ru/CubiCal#71]
The proper way to build a Cython based project is to bundle the C files, and don't generate them by default. That way the project is installable without Cython installed.

http://cython.readthedocs.io/en/latest/src/reference/compilation.html#distributing-cython-modules

**Comment by JSKenyon** [comment]
Fixed in #89.

**Comment by o-smirnov** [comment]
I'm not happy with the present setup. I just did a ``pip install -e`` with the latest master, and ``git status`` now shows all sorts of differences:

```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
	modified:   cubical/kernels/cychain.c
	modified:   cubical/kernels/cyf_slope.cpp
	modified:   cubical/kernels/cyfull_W_complex.c
	modified:   cubical/kernels/cyfull_complex.c
	modified:   cubical/kernels/cyphase_only.c
	modified:   cubical/kernels/cyt_slope.cpp
	modified:   cubical/kernels/cytf_plane.cpp
	modified:   cubical/tools/logger.py
```
Obviously it regenerated the files with cython, looking at ``git diff``, it's all bullshit like
```
-            "/home/jonathan/venvs/setupenv/local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h", 
-            "/home/jonathan/venvs/setupenv/local/lib/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h"
+            "/home/oms/.venv/cc1/local/lib/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h", 
+            "/home/oms/.venv/cc1/local/lib/python2.7/site-packages/numpy/core/include/numpy/ufuncobject.h"
```
I most emphatically do ***not*** want to be committing and pushing these changes. So how do we avoid this? @gijzelaerr help please. It was your suggestion to bundle the auto-generated code inside the package distribution -- question now is, how do we bundle this **without** committing auto-generated code to the repo?

**Comment by gijzelaerr** [comment]
I think it is because the setup.py script now checks if cpython is available. If it is available, it will compile these files.

What I would try to do is make the cythonize step explicit by adding a `python setup.py cythonize` subcommand using `cmdclass`.
