### ISSUE TITLE
Bad characters in log messages

### ISSUE THREAD

**Issue by JSKenyon** [ratt-ru/CubiCal#82]
The current log messages do not render nicely in most text editors e.g.

```
 - 05:41:11 - solver             | [1m[94m[P2] [0m[0m[2.5/3.0 3.6/4.9 6.4Gb] D0T0F0: G: 200 iters, conv 0.00% dE: 200 iters, conv 14.29% , stall 64.72%, g/fl 0.00%, d/fl 0.00%, chi2 1.323 -> 1.077 (1.1), noise 1.13 -> 1.12
```

I believe it has something to do with the colour options. Could we possibly fix this along with #74?

**Comment by o-smirnov** [comment]
Colour output can be disabled with ``--log-boring 1``. In interactive mode I find the colours quite helpful, but indeed it does not yield itself to cut-and-paste nicely... but I'm not sure if we can do anything beyond letting the user choose one or the other!

**Comment by IanHeywood** [comment]
Is it possible to re-open the log file at the very end and just strip out the colour switching characters?

**Comment by o-smirnov** [comment]
Hmmm... not a bad idea.... even better, we could strip them out on-the-fly as things are being rendered to the logfile. It's as simple as figuring out the right regex! (famous last wor-

**Comment by JSKenyon** [comment]
[This](https://docs.python.org/3/howto/logging-cookbook.html#logging-to-multiple-destinations) may be helpful. We could have a different formatter for the terminal output and the log file. Might be more elegant than editing it after the fact.

**Comment by o-smirnov** [comment]
Yeah this is definitely the right way to do it. Let me have a poke around. We use the same logger in DDFacet, so I'd rather have the same "elegant" solution for both.
