### ISSUE TITLE
compilation fails due to missing boost-python requirement

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/CubiCal#9]
Or at least that's my guess as to the cause:

```    
src/fit.cc:28:28: fatal error: boost/python.hpp: No such file or directory
```

**Comment by JSKenyon** [comment]
@o-smirnov Finally figured this one out. It is not a problem if python-casacore is installed from KERN2 as it installs all the supporting infrastructure. Attempting to install python-casacore via pip doesn't include all its dependencies. I think that I will make installing it via KERN a requirement for installing CubiCal. As it has to be apt-get installed, it cannot go into setup.py. This should be simpler once it is packaged.
